# Scrape healthcare.by

In [5]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [29]:
import re

In [6]:
url = "https://healthcare.by/search.php?typ=707&sort=1"

In [41]:
fap = "https://healthcare.by/search.php?typ=707&sort=1&page=" 
amb = "https://healthcare.by/search.php?typ=600&sort=1&page=" 
hospital = "https://healthcare.by/search.php?typ=603&sort=1&page="
polyclinic = "https://healthcare.by/search.php?typ=598&sort=1&page="

In [42]:
links = [fap, amb, hospital, polyclinic]

In [9]:
response = requests.get(url)
doc = BeautifulSoup(response.text)

In [10]:
doc

<html>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="ru" http-equiv="Content-Language"/>
<title>Здравоохранение Беларуси — результаты поиска</title>
<meta content="noindex" name="robots"/>
<meta content="" name="description"/>
<meta content="здравоохранение,беларусь,каталог,медицина,поиск" name="keywords"/>
<link href="styles/main.css" rel="stylesheet"/>
<script src="scripts/main.js"></script>
</head>
<body bgcolor="white">
<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
    (function(w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter10063810 = new Ya.Metrika({id:10063810, enableAll: true});
            }
            catch(e) { }
        });
    })(window, "yandex_metrika_callbacks");
    </script></div>
<script defer="defer" src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<noscript><div><img alt="" src="//mc.yandex.ru/watch/10063810" style="position:absolute; left:-9999px;"/></div></noscript>
<!-- /Yandex.Metrika counter -->
<!--Googl Analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-84817079-1', 'auto');
  ga('send', 'pageview');

</script>
<!--/Googl Analytics-->
<table background="images/Bkg.gif" cellpadding="0" cellspacing="0" width="100%"><tr>
<td width="20%"></td>
<td align="center" width="60%"><img height="21" src="images/Head2.gif" width="400"/></td>
<td align="right" valign="center" width="20%">
</td>
</tr></table>
<table style="border-bottom: 1pt solid #4682B4;" width="100%"><tr><td style="font-size: 10pt;">
<table border="0" width="100%"><tr><td align="left" valign="top" width="550"><form action="fastsearch.php" method="get">Быстрый поиск:<br/>
<input id="fastsearch" maxlength="255" name="srch" style="width: 200pt;" type="text" value=""/>
<input type="submit" value="Искать"/>
<a href="fastsearchhelp.php" target="_new"><img alt="Справка по быстрому поиску" border="0" height="20" onmouseout="this.src='images/help.gif'" onmouseover="this.src='images/help1.gif'" src="images/help.gif" width="20"/></a>
<a href="advsearch.php"><img alt="Расширенный поиск" border="0" height="20" onmouseout="this.src='images/advsearch.gif'" onmouseover="this.src='images/advsearch1.gif'" src="images/advsearch.gif" width="20"/></a>
<a href="rubricator.php"><img alt="Рубрикатор" border="0" height="20" onmouseout="this.src='images/rubr.gif'" onmouseover="this.src='images/rubr1.gif'" src="images/rubr.gif" width="20"/></a>
<a href="map.php"><img alt="Поиск по карте" border="0" height="20" onmouseout="this.src='images/map.gif'" onmouseover="this.src='images/map1.gif'" src="images/map.gif" width="20"/></a><br/>
область поиска: <input id="inst" name="inst" onclick="if (!this.checked) document.getElementById('all').checked=false;" type="checkbox"/>организации
<input id="dept" name="dept" onclick="if (!this.checked) document.getElementById('all').checked=false;" type="checkbox"/>подразделения
<!--
<input type="checkbox" name="prsn" id="prsn"
 onclick="if (!this.checked) document.getElementById('all').checked=false;"/>специалисты
-->
<input id="all" onclick="if (this.checked) {document.getElementById('inst').checked = true;document.getElementById('dept').checked = true;document.getElementById('prsn').checked = true;} else {document.getElementById('inst').checked = false;document.getElementById('dept').checked = false;document.getElementById('prsn').checked = false;}" type="checkbox"/>везде<br/>
режим поиска: <input checked="checked" name="mode" type="radio" value="and"/> все слова
<input name="mode" type="radio" value="or"/> любое слово
</form>
</td><td align="left"><script language="javascript" src="AC_RunActiveContent.js"></script>
</td></tr></table><!--
<table width=100%>
<TR><TD colspan=2 BGCOLOR=#4682B4 height="1"></TD></TR>
<TR><TD align="center" valign="top" width="50%"><a href="http://med.by/press/zb2015">Приобрести печатную версию каталога "Здравоохранение Беларуси"</a></TD>
<TD align="center" valign="top" width="50%"><a href="http://med.by/press/reklama_zala">Актовый зал в центре Минска в аренду</a></TD></TR>
</TABLE>
-->
</td></tr></table>
<p style="font-size: 9pt"><b>Организаций: 2100</b></p><p style="font-size: 9pt"><a href="advsearch.php">Новый поиск</a> | <a href="advsearch.php?typ=707">Повторный поиск</a></p><p style="font-size: 9pt">Сортировать по: <span style="font-weight: bold">названию</span> | <a href="search.php?typ=707&amp;page=1&amp;sort=2">регионам</a> | <a href="search.php?typ=707&amp;page=1&amp;sort=3">административному уровню</a></p><ol start="1"><li style="font-size: 10pt"><a href="instinfo.php?orgnum=16445">Агеевский ФАП</a> (Агеевка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=17185">Адамовский ФАП</a> (Адамово)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=18082">Адаховщинский ФАП</a> (Адаховщина)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15701">Азделинский ФАП</a> (Азделино)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15299">Азинский ФАП</a> (Азино)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=16081">Александровский ФАП</a> (Александровка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15850">Александровский ФАП</a> (Александровка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=17747">Алексеевичский ФАП</a> (Алексеевичи)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15416">Алексиничский ФАП</a> (Алексиничи)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=16950">Алешковичский ФАП</a> (Олешковичи)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=14945">Альбянский ФАП</a> (Биозавода)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15506">Амбросовичский ФАП</a> (Амбросовичи)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=29157">Амховский ФАП, ФАП</a> (Амховая 1-я)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15117">Ананичский ФАП</a> (Ананичи)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=17327">Ананчицкий ФАП</a> (Ананчицы)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15338">Андроновский ФАП</a> (Андроны)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15810">Антоновский ФАП</a> (Антоновка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=15756">Антоновский ФАП</a> (Антоновка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=16661">Антоновский ФАП</a> (Антоновка)</li><li style="font-size: 10pt"><a href="instinfo.php?orgnum=16322">Антоновский ФАП</a> (Антоновка)</li></ol><p class="paginator">Страницы: <span class="paginator-current">1</span> <a class="paginator-pages" href="search.php?typ=707&amp;&amp;page=2&amp;sort=1">2</a> <a class="paginator-pages" href="search.php?typ=707&amp;&amp;page=3&amp;sort=1">3</a> <a class="paginator-pages" href="search.php?typ=707&amp;&amp;page=4&amp;sort=1">4</a> <span class="paginator-dotted">...</span><a class="paginator-next" href="search.php?typ=707&amp;&amp;page=2&amp;sort=1">&gt;</a> <a class="paginator-last" href="search.php?typ=707&amp;&amp;page=105&amp;sort=1">Последняя</a> </p><table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr bgcolor="#4682B4" height="21">
<td align="center" style="color: white; font-size: 8pt; font-weight: bold;">
<a href="/" style="color: white; font-size: 8pt; font-weight: bold;">в начало</a>
</td>
<td align="center">
<noindex><a href="http://www.med.by" style="color: white; font-size: 8pt; font-weight: bold;">med.by</a></noindex>
</td>
<td align="center">
<noindex><a href="http://www.med.by/about/our_banners/" style="color: white; font-size: 8pt; font-weight: bold;">баннеры</a></noindex>
</td>
<td align="center" style="color: white; font-size: 8pt; font-weight: bold;">
<a href="/advsearch.php" style="color: white; font-size: 8pt; font-weight: bold;">расширенный поиск</a>
</td>
<td align="center" style="color: white; font-size: 8pt; font-weight: bold;">
<noindex><a href="http://www.med.by/press/zb2015/" style="color: white; font-size: 8pt; font-weight: bold;">купить каталог</a></noindex>
</td>
</tr>
<tr bgcolor="white"><td align="center" colspan="6" style="padding-top:5px;">
<div style="font-size: 8pt;margin: 5px 0;">© 1995-2026, <a href="/deptinfo.php?deptnum=14425">научно-информационный отдел ГУ «Республиканская научная медицинская библиотека»</a></div>
</td></tr>
<!--Счетчики-->
<tr><td align="center" colspan="7">
<noindex>
<!-- All.By -->
<!-- BEGIN Rating All.BY CODE - ALTERNATING THIS CODE WILL CAUSE TERMINATION ACCOUNT-->
<a href="http://www.all.by/">
<img alt="Rating All.BY" border="0" height="32" src="http://www.all.by/cgi-bin/rating.cgi?id=10013205" width="90"/></a>
<!-- END Rating All.BY CODE-->
<!-- Akavita -->
<!-- Akavita counter co7de --><a href="http://adlik.akavita.com/bin/link?id=2724" target="_top">
<script language="javascript"><!--
d=document;w=window;n=navigator;d.cookie="cc=1";
r=''+escape(d.referrer);js=10;c=(d.cookie)?1:0;j=0;
x=Math.random();u=''+escape(w.location.href);lt=0;
h=history.length;t=new Date;f=(self!=top)?1:0;cd=0;
tz=t.getTimezoneOffset();cpu=n.cpuClass;ww=wh=ss=0;
//--></script><script language="javascript1.1"><!--
js=11;j=(n.javaEnabled()?1:0);
//--></script><script language="javascript1.2"><!--
js=12;lt=1;s=screen;ss=s.width;
cd=(s.colorDepth?s.colorDepth:s.pixelDepth);
//--></script><script language="javascript1.3"><!--
js=13;wh=w.innerHeight;ww=w.innerWidth;
wh=(wh?wh:d.documentElement.offsetHeight);
ww=(ww?ww:d.documentElement.offsetWidth);
//--></script><script language="javascript"><!--
q='lik?id=2724&d='+u+'&r='+r+'&h='+h+'&f='+f;
q+='&c='+c+'&tz='+tz+'&cpu='+cpu+'&js='+js+'&wh='+wh;
q+='&ww='+ww+'&ss='+ss+'&cd='+cd+'&j='+j+'&x='+x;
d.write('<img src="http://adlik.akavita.com/bin/'+
q+'" alt="Akavita" '+
'border=0 width=88 height=31>');
if(lt){d.write('<'+'!-- ');}//--></script><noscript>
<img alt="Akavita" border="0" height="31" src="http://adlik.akavita.com/bin/lik?id=2724" width="88"/>
</noscript><script language="JavaScript"><!--
if(lt){d.write('--'+'>');}//--></script></a>
<!-- Akavita counter code -->
<!-- Rambler -->
<!--begin of Top100 logo-->
<a href="http://top100.rambler.ru/top100/">
<img alt="Rambler's Top100" border="0" height="31" src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-blue.gif" width="88"/></a>
<!--end of Top100 logo -->
<!-- Mail.Ru -->
<!--Rating@Mail.ru COUNTER--><script language="JavaScript"><!--
d=document;a='';a+=';r='+escape(d.referrer)
js=10//--></script><script language="JavaScript1.1"><!--
a+=';j='+navigator.javaEnabled()
js=11//--></script><script language="JavaScript1.2"><!--
s=screen;a+=';s='+s.width+'*'+s.height
a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
js=12//--></script><script language="JavaScript1.3"><!--
js=13//--></script><script language="JavaScript"><!--
d.write('<a href="http://top.mail.ru/jump?from=374253"'+
' target=_top><img src="http://top.list.ru/counter'+
'?id=374253;t=210;js='+js+a+';rand='+Math.random()+
'" alt="Рейтинг@Mail.ru"'+' border=0 height=31 width=88></a>')
if(js>11)d.write('<'+'!-- ')//--></script><noscript><a href="http://top.mail.ru/jump?from=374253" target="_top"><img alt="Рейтинг@Mail.ru" border="0" height="31" src="http://top.list.ru/counter?js=na;id=374253;t=210" width="88"/></a></noscript><script language="JavaScript"><!--
if(js>11)d.write('--'+'>')//--></script><!--/COUNTER--><!--begin of Top100-->
<a href="http://top100.rambler.ru/top100/">
<img alt="Rambler's Top100" border="0" height="1" src="http://counter.rambler.ru/top100.cnt?360720" width="1"/></a>
<!--end of Top100 code-->
<!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=10063810&amp;from=informer" rel="nofollow" target="_blank"><img alt="Яндекс.Метрика" onclick="try{Ya.Metrika.informer({i:this,id:10063810,type:0,lang:'ru'});return false}catch(e){}" src="//bs.yandex.ru/informer/10063810/3_1_66A2D4FF_4682B4FF_1_pageviews" style="width:88px; height:31px; border:0;" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"/></a>
<!-- /Yandex.Metrika informer -->
</noindex>
</td></tr>
<!--Счетчики-->
</table>
</body>
</html>

In [11]:
items = doc.select("li")

In [12]:
items

[<li style="font-size: 10pt"><a href="instinfo.php?orgnum=16445">Агеевский ФАП</a> (Агеевка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=17185">Адамовский ФАП</a> (Адамово)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=18082">Адаховщинский ФАП</a> (Адаховщина)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15701">Азделинский ФАП</a> (Азделино)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15299">Азинский ФАП</a> (Азино)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=16081">Александровский ФАП</a> (Александровка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15850">Александровский ФАП</a> (Александровка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=17747">Алексеевичский ФАП</a> (Алексеевичи)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15416">Алексиничский ФАП</a> (Алексиничи)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=16950">Алешковичский ФАП</a> (Олешковичи)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=14945">Альбянский ФАП</a> (Биозавода)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15506">Амбросовичский ФАП</a> (Амбросовичи)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=29157">Амховский ФАП, ФАП</a> (Амховая 1-я)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15117">Ананичский ФАП</a> (Ананичи)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=17327">Ананчицкий ФАП</a> (Ананчицы)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15338">Андроновский ФАП</a> (Андроны)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15810">Антоновский ФАП</a> (Антоновка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=15756">Антоновский ФАП</a> (Антоновка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=16661">Антоновский ФАП</a> (Антоновка)</li>,
 <li style="font-size: 10pt"><a href="instinfo.php?orgnum=16322">Антоновский ФАП</a> (Антоновка)</li>]

In [21]:
items[0].find("a").next_sibling.strip(" \xa0()")

'Агеевка'

In [23]:
for item in items:
    print("----")
    print(item.select_one("a").get_text()) #name
    print(f"https://healthcare.by/{item.select_one("a")['href']}") #link
    print(item.find("a").next_sibling.strip(" \xa0()")) #town

----
Агеевский ФАП
https://healthcare.by/instinfo.php?orgnum=16445
Агеевка
----
Адамовский ФАП
https://healthcare.by/instinfo.php?orgnum=17185
Адамово
----
Адаховщинский ФАП
https://healthcare.by/instinfo.php?orgnum=18082
Адаховщина
----
Азделинский ФАП
https://healthcare.by/instinfo.php?orgnum=15701
Азделино
----
Азинский ФАП
https://healthcare.by/instinfo.php?orgnum=15299
Азино
----
Александровский ФАП
https://healthcare.by/instinfo.php?orgnum=16081
Александровка
----
Александровский ФАП
https://healthcare.by/instinfo.php?orgnum=15850
Александровка
----
Алексеевичский ФАП
https://healthcare.by/instinfo.php?orgnum=17747
Алексеевичи
----
Алексиничский ФАП
https://healthcare.by/instinfo.php?orgnum=15416
Алексиничи
----
Алешковичский ФАП
https://healthcare.by/instinfo.php?orgnum=16950
Олешковичи
----
Альбянский ФАП
https://healthcare.by/instinfo.php?orgnum=14945
Биозавода
----
Амбросовичский ФАП
https://healthcare.by/instinfo.php?orgnum=15506
Амбросовичи
----
Амховский ФАП, ФАП
https://healthcare.by/instinfo.php?orgnum=29157
Амховая 1-я
----
Ананичский ФАП
https://healthcare.by/instinfo.php?orgnum=15117
Ананичи
----
Ананчицкий ФАП
https://healthcare.by/instinfo.php?orgnum=17327
Ананчицы
----
Андроновский ФАП
https://healthcare.by/instinfo.php?orgnum=15338
Андроны
----
Антоновский ФАП
https://healthcare.by/instinfo.php?orgnum=15810
Антоновка
----
Антоновский ФАП
https://healthcare.by/instinfo.php?orgnum=15756
Антоновка
----
Антоновский ФАП
https://healthcare.by/instinfo.php?orgnum=16661
Антоновка
----
Антоновский ФАП
https://healthcare.by/instinfo.php?orgnum=16322
Антоновка

In [24]:
def get_facility_type(name):
    name = name.lower().replace("ё", "е")

    facility_types = {
        "ФАП": ("FAP", ("фап", "фельдшерско-акушерский пункт")),
        "Амбулатория": ("Outpatient Clinic", ("амбулатория", "АВОП", "авоп", "ВАП", "вап")),
        "Больница": ("Hospital", ("больница",)),
        "Поликлиника": ("Polyclinic", ("поликлиника",)),
    }

    for facility_type, (type_eng, keywords) in facility_types.items():
        if any(keyword in name for keyword in keywords):
            return facility_type, type_eng

    return None, None

In [25]:
#Building a list of dictionaries

rows = []

for item in items:
    name = item.select_one("a").get_text(" ", strip=True)
    facility_type, type_eng = get_facility_type(name)
    row = {
        'facility_title': item.select_one("a").get_text(),
        'link': f"https://healthcare.by/{item.select_one("a")['href']}",
        'settlement': item.find("a").next_sibling.strip(" \xa0()"),
        'facility_type': facility_type,
        'facility_type_eng': type_eng
    }
    rows.append(row)
rows

[{'facility_title': 'Агеевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16445',
  'settlement': 'Агеевка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Адамовский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17185',
  'settlement': 'Адамово',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Адаховщинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=18082',
  'settlement': 'Адаховщина',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Азделинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15701',
  'settlement': 'Азделино',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Азинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15299',
  'settlement': 'Азино',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Александровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16081',
  'settlement': 'Александровка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Александровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15850',
  'settlement': 'Александровка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Алексеевичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17747',
  'settlement': 'Алексеевичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Алексиничский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15416',
  'settlement': 'Алексиничи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Алешковичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16950',
  'settlement': 'Олешковичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Альбянский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=14945',
  'settlement': 'Биозавода',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Амбросовичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15506',
  'settlement': 'Амбросовичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Амховский ФАП, ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=29157',
  'settlement': 'Амховая 1-я',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Ананичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15117',
  'settlement': 'Ананичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Ананчицкий ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17327',
  'settlement': 'Ананчицы',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Андроновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15338',
  'settlement': 'Андроны',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15810',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15756',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16661',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16322',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP'}]

In [43]:
# base_url = fap
# # Открываем первую страницу и определяем количество страниц
# response = requests.get(f"{base_url}1")
# doc = BeautifulSoup(response.text, "html.parser")

# page_numbers = []

# for link in doc.select('a[href*="page="]'):
#     match = re.search(r"page=(\d+)", link.get("href", ""))

#     if match:
#         page_numbers.append(int(match.group(1)))

# last_page = max(page_numbers, default=1)

# print("Количество страниц:", last_page)

Количество страниц: 105

In [45]:
rows = []

for category_url in links:
    base_url = category_url.split("&page=")[0]

    response = requests.get(base_url, params={"page": 1})
    doc = BeautifulSoup(response.text, "html.parser")

    page_numbers = []

    for page_link in doc.select('a[href*="page="]'):
        match = re.search(r"page=(\d+)", page_link.get("href", ""))

        if match:
            page_numbers.append(int(match.group(1)))

    last_page = max(page_numbers, default=1)
    print("Количество страниц:", last_page)

    for page in range(1, last_page + 1):
        response = requests.get(
            base_url,
            params={"page": page},
            timeout=30
        )
        response.raise_for_status()

        print(response.url)

        doc = BeautifulSoup(response.text, "html.parser")
        items = doc.select("li")

        for item in items:
            facility_link = item.select_one("a")

            if facility_link is None:
                continue

            name = facility_link.get_text(" ", strip=True)
            facility_type, type_eng = get_facility_type(name)

            row = {
                "facility_title": name,
                "link": f"https://healthcare.by/{facility_link['href']}",
                "settlement": facility_link.next_sibling.strip(" \xa0()"),
                "facility_type": facility_type,
                "facility_type_eng": type_eng,
            }

            rows.append(row)

Количество страниц: 105
https://healthcare.by/search.php?typ=707&sort=1&page=1
https://healthcare.by/search.php?typ=707&sort=1&page=2
https://healthcare.by/search.php?typ=707&sort=1&page=3
https://healthcare.by/search.php?typ=707&sort=1&page=4
https://healthcare.by/search.php?typ=707&sort=1&page=5
https://healthcare.by/search.php?typ=707&sort=1&page=6
https://healthcare.by/search.php?typ=707&sort=1&page=7
https://healthcare.by/search.php?typ=707&sort=1&page=8
https://healthcare.by/search.php?typ=707&sort=1&page=9
https://healthcare.by/search.php?typ=707&sort=1&page=10
https://healthcare.by/search.php?typ=707&sort=1&page=11
https://healthcare.by/search.php?typ=707&sort=1&page=12
https://healthcare.by/search.php?typ=707&sort=1&page=13
https://healthcare.by/search.php?typ=707&sort=1&page=14
https://healthcare.by/search.php?typ=707&sort=1&page=15
https://healthcare.by/search.php?typ=707&sort=1&page=16
https://healthcare.by/search.php?typ=707&sort=1&page=17
https://healthcare.by/search.php?typ=707&sort=1&page=18
https://healthcare.by/search.php?typ=707&sort=1&page=19
https://healthcare.by/search.php?typ=707&sort=1&page=20
https://healthcare.by/search.php?typ=707&sort=1&page=21
https://healthcare.by/search.php?typ=707&sort=1&page=22
https://healthcare.by/search.php?typ=707&sort=1&page=23
https://healthcare.by/search.php?typ=707&sort=1&page=24
https://healthcare.by/search.php?typ=707&sort=1&page=25
https://healthcare.by/search.php?typ=707&sort=1&page=26
https://healthcare.by/search.php?typ=707&sort=1&page=27
https://healthcare.by/search.php?typ=707&sort=1&page=28
https://healthcare.by/search.php?typ=707&sort=1&page=29
https://healthcare.by/search.php?typ=707&sort=1&page=30
https://healthcare.by/search.php?typ=707&sort=1&page=31
https://healthcare.by/search.php?typ=707&sort=1&page=32
https://healthcare.by/search.php?typ=707&sort=1&page=33
https://healthcare.by/search.php?typ=707&sort=1&page=34
https://healthcare.by/search.php?typ=707&sort=1&page=35
https://healthcare.by/search.php?typ=707&sort=1&page=36
https://healthcare.by/search.php?typ=707&sort=1&page=37
https://healthcare.by/search.php?typ=707&sort=1&page=38
https://healthcare.by/search.php?typ=707&sort=1&page=39
https://healthcare.by/search.php?typ=707&sort=1&page=40
https://healthcare.by/search.php?typ=707&sort=1&page=41
https://healthcare.by/search.php?typ=707&sort=1&page=42
https://healthcare.by/search.php?typ=707&sort=1&page=43
https://healthcare.by/search.php?typ=707&sort=1&page=44
https://healthcare.by/search.php?typ=707&sort=1&page=45
https://healthcare.by/search.php?typ=707&sort=1&page=46
https://healthcare.by/search.php?typ=707&sort=1&page=47
https://healthcare.by/search.php?typ=707&sort=1&page=48
https://healthcare.by/search.php?typ=707&sort=1&page=49
https://healthcare.by/search.php?typ=707&sort=1&page=50
https://healthcare.by/search.php?typ=707&sort=1&page=51
https://healthcare.by/search.php?typ=707&sort=1&page=52
https://healthcare.by/search.php?typ=707&sort=1&page=53
https://healthcare.by/search.php?typ=707&sort=1&page=54
https://healthcare.by/search.php?typ=707&sort=1&page=55
https://healthcare.by/search.php?typ=707&sort=1&page=56
https://healthcare.by/search.php?typ=707&sort=1&page=57
https://healthcare.by/search.php?typ=707&sort=1&page=58
https://healthcare.by/search.php?typ=707&sort=1&page=59
https://healthcare.by/search.php?typ=707&sort=1&page=60
https://healthcare.by/search.php?typ=707&sort=1&page=61
https://healthcare.by/search.php?typ=707&sort=1&page=62
https://healthcare.by/search.php?typ=707&sort=1&page=63
https://healthcare.by/search.php?typ=707&sort=1&page=64
https://healthcare.by/search.php?typ=707&sort=1&page=65
https://healthcare.by/search.php?typ=707&sort=1&page=66
https://healthcare.by/search.php?typ=707&sort=1&page=67
https://healthcare.by/search.php?typ=707&sort=1&page=68
https://healthcare.by/search.php?typ=707&sort=1&page=69
https://healthcare.by/search.php?typ=707&sort=1&page=70
https://healthcare.by/search.php?typ=707&sort=1&page=71
https://healthcare.by/search.php?typ=707&sort=1&page=72
https://healthcare.by/search.php?typ=707&sort=1&page=73
https://healthcare.by/search.php?typ=707&sort=1&page=74
https://healthcare.by/search.php?typ=707&sort=1&page=75
https://healthcare.by/search.php?typ=707&sort=1&page=76
https://healthcare.by/search.php?typ=707&sort=1&page=77
https://healthcare.by/search.php?typ=707&sort=1&page=78
https://healthcare.by/search.php?typ=707&sort=1&page=79
https://healthcare.by/search.php?typ=707&sort=1&page=80
https://healthcare.by/search.php?typ=707&sort=1&page=81
https://healthcare.by/search.php?typ=707&sort=1&page=82
https://healthcare.by/search.php?typ=707&sort=1&page=83
https://healthcare.by/search.php?typ=707&sort=1&page=84
https://healthcare.by/search.php?typ=707&sort=1&page=85
https://healthcare.by/search.php?typ=707&sort=1&page=86
https://healthcare.by/search.php?typ=707&sort=1&page=87
https://healthcare.by/search.php?typ=707&sort=1&page=88
https://healthcare.by/search.php?typ=707&sort=1&page=89
https://healthcare.by/search.php?typ=707&sort=1&page=90
https://healthcare.by/search.php?typ=707&sort=1&page=91
https://healthcare.by/search.php?typ=707&sort=1&page=92
https://healthcare.by/search.php?typ=707&sort=1&page=93
https://healthcare.by/search.php?typ=707&sort=1&page=94
https://healthcare.by/search.php?typ=707&sort=1&page=95
https://healthcare.by/search.php?typ=707&sort=1&page=96
https://healthcare.by/search.php?typ=707&sort=1&page=97
https://healthcare.by/search.php?typ=707&sort=1&page=98
https://healthcare.by/search.php?typ=707&sort=1&page=99
https://healthcare.by/search.php?typ=707&sort=1&page=100
https://healthcare.by/search.php?typ=707&sort=1&page=101
https://healthcare.by/search.php?typ=707&sort=1&page=102
https://healthcare.by/search.php?typ=707&sort=1&page=103
https://healthcare.by/search.php?typ=707&sort=1&page=104
https://healthcare.by/search.php?typ=707&sort=1&page=105
Количество страниц: 30
https://healthcare.by/search.php?typ=600&sort=1&page=1
https://healthcare.by/search.php?typ=600&sort=1&page=2
https://healthcare.by/search.php?typ=600&sort=1&page=3
https://healthcare.by/search.php?typ=600&sort=1&page=4
https://healthcare.by/search.php?typ=600&sort=1&page=5
https://healthcare.by/search.php?typ=600&sort=1&page=6
https://healthcare.by/search.php?typ=600&sort=1&page=7
https://healthcare.by/search.php?typ=600&sort=1&page=8
https://healthcare.by/search.php?typ=600&sort=1&page=9
https://healthcare.by/search.php?typ=600&sort=1&page=10
https://healthcare.by/search.php?typ=600&sort=1&page=11
https://healthcare.by/search.php?typ=600&sort=1&page=12
https://healthcare.by/search.php?typ=600&sort=1&page=13
https://healthcare.by/search.php?typ=600&sort=1&page=14
https://healthcare.by/search.php?typ=600&sort=1&page=15
https://healthcare.by/search.php?typ=600&sort=1&page=16
https://healthcare.by/search.php?typ=600&sort=1&page=17
https://healthcare.by/search.php?typ=600&sort=1&page=18
https://healthcare.by/search.php?typ=600&sort=1&page=19
https://healthcare.by/search.php?typ=600&sort=1&page=20
https://healthcare.by/search.php?typ=600&sort=1&page=21
https://healthcare.by/search.php?typ=600&sort=1&page=22
https://healthcare.by/search.php?typ=600&sort=1&page=23
https://healthcare.by/search.php?typ=600&sort=1&page=24
https://healthcare.by/search.php?typ=600&sort=1&page=25
https://healthcare.by/search.php?typ=600&sort=1&page=26
https://healthcare.by/search.php?typ=600&sort=1&page=27
https://healthcare.by/search.php?typ=600&sort=1&page=28
https://healthcare.by/search.php?typ=600&sort=1&page=29
https://healthcare.by/search.php?typ=600&sort=1&page=30
Количество страниц: 28
https://healthcare.by/search.php?typ=603&sort=1&page=1
https://healthcare.by/search.php?typ=603&sort=1&page=2
https://healthcare.by/search.php?typ=603&sort=1&page=3
https://healthcare.by/search.php?typ=603&sort=1&page=4
https://healthcare.by/search.php?typ=603&sort=1&page=5
https://healthcare.by/search.php?typ=603&sort=1&page=6
https://healthcare.by/search.php?typ=603&sort=1&page=7
https://healthcare.by/search.php?typ=603&sort=1&page=8
https://healthcare.by/search.php?typ=603&sort=1&page=9
https://healthcare.by/search.php?typ=603&sort=1&page=10
https://healthcare.by/search.php?typ=603&sort=1&page=11
https://healthcare.by/search.php?typ=603&sort=1&page=12
https://healthcare.by/search.php?typ=603&sort=1&page=13
https://healthcare.by/search.php?typ=603&sort=1&page=14
https://healthcare.by/search.php?typ=603&sort=1&page=15
https://healthcare.by/search.php?typ=603&sort=1&page=16
https://healthcare.by/search.php?typ=603&sort=1&page=17
https://healthcare.by/search.php?typ=603&sort=1&page=18
https://healthcare.by/search.php?typ=603&sort=1&page=19
https://healthcare.by/search.php?typ=603&sort=1&page=20
https://healthcare.by/search.php?typ=603&sort=1&page=21
https://healthcare.by/search.php?typ=603&sort=1&page=22
https://healthcare.by/search.php?typ=603&sort=1&page=23
https://healthcare.by/search.php?typ=603&sort=1&page=24
https://healthcare.by/search.php?typ=603&sort=1&page=25
https://healthcare.by/search.php?typ=603&sort=1&page=26
https://healthcare.by/search.php?typ=603&sort=1&page=27
https://healthcare.by/search.php?typ=603&sort=1&page=28
Количество страниц: 14
https://healthcare.by/search.php?typ=598&sort=1&page=1
https://healthcare.by/search.php?typ=598&sort=1&page=2
https://healthcare.by/search.php?typ=598&sort=1&page=3
https://healthcare.by/search.php?typ=598&sort=1&page=4
https://healthcare.by/search.php?typ=598&sort=1&page=5
https://healthcare.by/search.php?typ=598&sort=1&page=6
https://healthcare.by/search.php?typ=598&sort=1&page=7
https://healthcare.by/search.php?typ=598&sort=1&page=8
https://healthcare.by/search.php?typ=598&sort=1&page=9
https://healthcare.by/search.php?typ=598&sort=1&page=10
https://healthcare.by/search.php?typ=598&sort=1&page=11
https://healthcare.by/search.php?typ=598&sort=1&page=12
https://healthcare.by/search.php?typ=598&sort=1&page=13
https://healthcare.by/search.php?typ=598&sort=1&page=14

In [46]:
len(rows)

3501

In [47]:
df = pd.DataFrame(rows)

In [48]:
df.duplicated().sum()

np.int64(4)

In [49]:
# Фильтруем df, чтобы оставить все строки, которые где-либо повторяются (keep=False)
duplicates_df = df[df.duplicated(keep=False)]

# Сортируем их по всем колонкам для визуального объединения пар
duplicates_df = duplicates_df.sort_values(by=duplicates_df.columns.tolist())

# Показываем результат
duplicates_df

,facility_title,link,settlement,facility_type,facility_type_eng
17,Антоновский ФАП,https://healthcare.by/instinfo.php?orgnum=15810,Антоновка,ФАП,FAP
20,Антоновский ФАП,https://healthcare.by/instinfo.php?orgnum=15810,Антоновка,ФАП,FAP
596,Запольский ФАП,https://healthcare.by/instinfo.php?orgnum=15285,Заполье,ФАП,FAP
600,Запольский ФАП,https://healthcare.by/instinfo.php?orgnum=15285,Заполье,ФАП,FAP
1259,Октябрьский ФАП,https://healthcare.by/instinfo.php?orgnum=17342,Октябрь,ФАП,FAP
1260,Октябрьский ФАП,https://healthcare.by/instinfo.php?orgnum=17342,Октябрь,ФАП,FAP
1319,Павловичский ФАП,https://healthcare.by/instinfo.php?orgnum=16201,Павловичи,ФАП,FAP
1320,Павловичский ФАП,https://healthcare.by/instinfo.php?orgnum=16201,Павловичи,ФАП,FAP

In [50]:
df = df.drop_duplicates(subset="link").reset_index(drop=True)

In [51]:
len(df)

3497

In [54]:
rows = df.to_dict("records")

In [55]:
for row in rows:
    # Open the facility page
    response = requests.get(row["link"])
    doc = BeautifulSoup(response.text, "html.parser")

    # Find the first paragraph containing a <b> tag
    info = next(
        (p for p in doc.find_all("p") if p.find("b")),
        None
    )

    # Default values if the data is not available
    address = None
    website = None

    if info:
        # Extract all text parts from the paragraph
        text_parts = list(info.stripped_strings)

        # The first text after the facility name is the address
        if len(text_parts) > 1:
            address = text_parts[1].replace("\xa0", " ").strip()

        # Find an external website link
        website_tag = info.select_one(
            'a[href^="http://"], a[href^="https://"]'
        )

        if website_tag:
            website = website_tag.get("href")

    # Add the extracted values to the existing row
    row["address"] = address
    row["website"] = website

In [56]:
rows

[{'facility_title': 'Агеевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16445',
  'settlement': 'Агеевка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Сиреневая, 9, 213114, д. Агеевка, Могилевский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Адамовский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17185',
  'settlement': 'Адамово',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Адамово, Воложинский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Адаховщинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=18082',
  'settlement': 'Адаховщина',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'пер. Парковый, 10, 225372, д. Адаховщина, Ляховичский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Азделинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15701',
  'settlement': 'Азделино',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Новая, 1а, 247025, д. Азделино, Гомельский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Азинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15299',
  'settlement': 'Азино',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '211424, д. Азино, Полоцкий р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Александровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16081',
  'settlement': 'Александровка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. 9А, 247507, д. Александровка, Речицкий р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Александровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15850',
  'settlement': 'Александровка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Первомайская, 85, 247718, д. Александровка, Калинковичский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Алексеевичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17747',
  'settlement': 'Алексеевичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Ленина, 18, 225834, д. Алексеевичи, Дрогичинский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Алексиничский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15416',
  'settlement': 'Алексиничи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Алексиничи, Сенненский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Алешковичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16950',
  'settlement': 'Олешковичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '213170, д. Олешковичи, Белыничский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Альбянский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=14945',
  'settlement': 'Биозавода',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'п. Биозавода, Несвижский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Амбросовичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15506',
  'settlement': 'Амбросовичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '211262, д. Амбросовичи, Шумилинский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Амховский ФАП, ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=29157',
  'settlement': 'Амховая 1-я',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Молодежная, 5, 213109, д. Амховая 1-я, Могилевский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Ананичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15117',
  'settlement': 'Ананичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Ананичи, Пуховичский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Ананчицкий ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17327',
  'settlement': 'Ананчицы',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Козлова, 1, 223741, д. Ананчицы, Солигорский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Андроновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15338',
  'settlement': 'Андроны',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'Юньковский с/с, 211875, д. Андроны, Поставский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15849',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Советская, 44А, 247730, д. Антоновка, Калинковичский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15810',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Интернациональная, 12, 247248, д. Антоновка, Жлобинский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15756',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Комсомольская, 37, 247073, д. Антоновка, Добрушский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Антоновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16661',
  'settlement': 'Антоновка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Юбилейная, 5, 213220, д. Антоновка, Чаусский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Антопольевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15473',
  'settlement': 'Антополье',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Гагарина, 38, 211157, д. Антополье, Чашникский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Арабовщинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17630',
  'settlement': 'Арабовщина',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Карвата, 1, 225314, д. Арабовщина, Барановичский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Артуковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16080',
  'settlement': 'Артуки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Советская, 37а, 247503, д. Артуки, Речицкий р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Асаревичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15630',
  'settlement': 'Асаревичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Колхозная, 6, 247662, д. Асаревичи, Брагинский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Аталезский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16944',
  'settlement': 'Аталезь',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Мамонтова, 5, 222673, аг. Аталезь, Столбцовский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Ахремовская амбулатория врача общей практики',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15097',
  'settlement': 'Ахремовцы',
  'facility_type': 'Амбулатория',
  'facility_type_eng': 'Outpatient Clinic',
  'address': 'ул. Школьная, 76, 211972, д. Ахремовцы, Браславский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Б. Негновичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16887',
  'settlement': 'Большие Негновичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Центральная, д. Большие Негновичи, Борисовский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Б. Осовский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15324',
  'settlement': 'Большое Осово',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Большое Осово, Крупский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Бабировский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16060',
  'settlement': 'Бабирово',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'Кирова, 52, 213879, д. Бабирово, Глусский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Бабичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=28087',
  'settlement': 'Бабичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Садовая, 1, д. Бабичи, Чечерский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Бабичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16089',
  'settlement': 'Бабичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Мастрюкова, 17, 247534, д. Бабичи, Речицкий р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Бабуничский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16035',
  'settlement': 'Бабуничи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Шурина, 3, 247932, д. Бабуничи, Петриковский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Баевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15221',
  'settlement': 'Баево',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '211052, д. Баево, Дубровенский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Бакуновский-1 ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17389',
  'settlement': 'Бакуны-1',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Центральная, 71, 225142, д. Бакуны-1, Пружанский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Балашевичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16032',
  'settlement': 'Балашевичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'Ленина, 1, 213865, д. Балашевичи, Глусский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Балашовский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17227',
  'settlement': 'Балаши',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Малькевича, 16, д. Балаши, Вилейский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Барановичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16720',
  'settlement': 'Барановичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '231435, д. Барановичи, Кореличский р-н, Гродненская обл.',
  'website': None},
 {'facility_title': 'Барановский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=23533',
  'settlement': 'Бараново',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Бараново, Гродненский р-н, Гродненская обл.',
  'website': None},
 {'facility_title': 'Барбаровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16320',
  'settlement': 'Барбаров',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Молодежная, 10-1, 247753, д. Барбаров, Мозырский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Барсеевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15238',
  'settlement': 'Барсеево',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'Горбовский с/с, 211204, д. Барсеево, Лиозненский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Барсуковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15204',
  'settlement': 'Барсуки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Молодежная, 8, 211729, д. Барсуки, Докшицкий р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Барсуковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=7244',
  'settlement': 'Барсуки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '2136506, д. Барсуки, Климовичский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Барсуковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16370',
  'settlement': 'Барсуки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Центральная, 27а, д. Барсуки, Кировский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Барсуковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=14874',
  'settlement': 'Барсуки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Барсуки, Смолевичский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Барчицкий ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=18476',
  'settlement': 'Барчицы',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Садовая, 2а, д. Барчицы, Кировский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Барышевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16666',
  'settlement': 'Барышевка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Школьная, 57, кв. 4, 213202, д. Барышевка, Чаусский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Бастеновичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16555',
  'settlement': 'Бастеновичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '213484, д. Бастеновичи, Мстиславский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Бастунский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16534',
  'settlement': 'Бастуны',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '231371, д. Бастуны, Вороновский р-н, Гродненская обл.',
  'website': None},
 {'facility_title': 'Батченский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17965',
  'settlement': 'Батчи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Садовая, 14, 225874, д. Батчи, Кобринский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Бацуньский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15671',
  'settlement': 'Бацунь',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '247356, д. Бацунь, Буда-Кошелевский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Башневский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17711',
  'settlement': 'Башни',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Луговая, 20, 211279, д. Башни, Шумилинский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Безверховичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17138',
  'settlement': 'Безверховичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'р. Мурашки, 19, д. Безверховичи, Слуцкий р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Безуевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16088',
  'settlement': 'Безуев',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '247560, д. Безуев, 98 Речицкий р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Белановичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16043',
  'settlement': 'Белановичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Первомайская, 19А, 247903, д. Белановичи, Петриковский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Беларучский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16918',
  'settlement': 'Алекшицы',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '223114, д. Алекшицы, Логойский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Белевичский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17925',
  'settlement': 'Белевичи',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '213154, д. Белевичи, Могилевский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Белевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15784',
  'settlement': 'Белев',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Советская, 247962, д. Белев, Житковичский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Белицкий ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15811',
  'settlement': 'Белица',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Комсомольская, 18а, 247202, д. Белица, Жлобинский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Белоболотский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16090',
  'settlement': 'Белое Болото',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Молодежная, 23, 247514, д. Белое Болото, Речицкий р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Белодубровский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16348',
  'settlement': 'Белая Дуброва',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Школьная. 1, 213651, д. Белая Дуброва, Костюковичский р-н, Могилевская обл.',
  'website': None},
 {'facility_title': 'Белолипский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15417',
  'settlement': 'Белая Липа',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'д. Белая Липа, Сенненский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Белоусовщинский ФАП, ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=28879',
  'settlement': 'Белоусовщина',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Комсомольская, 14, 225178, свх. Белоусовщина, Пружанский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Бельковский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15340',
  'settlement': 'Бельки',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '211875, д. Бельки, Поставский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Бельковщинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15171',
  'settlement': 'Бельковщина',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '211621, д. Бельковщина, Верхнедвинский р-н, Витебская обл.',
  'website': None},
 {'facility_title': 'Бельский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16274',
  'settlement': 'Белая',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Советская, 21, 247763, д. Белая, Мозырский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Бельский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=17981',
  'settlement': 'Бельск',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Советская, 3, 225865, д. Бельск, Кобринский р-н, Брестская обл.',
  'website': None},
 {'facility_title': 'Беляевский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=28133',
  'settlement': 'Беляевка',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Новая,4, 247169, д. Беляевка, Чечерский р-н, Гомельская обл.',
  'website': None},
 {'facility_title': 'Белянский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16937',
  'settlement': 'Белое',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '223137, д. Белое, Логойский р-н, Минская обл.',
  'website': None},
 {'facility_title': 'Бенинский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=16791',
  'settlement': 'Бенин',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': 'ул. Приозерная, 7а, 231415, д. Бенин, Новогрудский р-н, Гродненская обл.',
  'website': None},
 {'facility_title': 'Бервеновский ФАП',
  'link': 'https://healthcare.by/instinfo.php?orgnum=15673',
  'settlement': 'Ховхло',
  'facility_type': 'ФАП',
  'facility_type_eng': 'FAP',
  'address': '247395, д. Ховхло, Буда-Кошелевский р-н, Гомельская обл.',
  'website': None},

In [57]:
df = pd.DataFrame(rows)

In [58]:
df

,facility_title,link,settlement,facility_type,facility_type_eng,address,website
0,Агеевский ФАП,https://healthcare.by/instinfo.php?orgnum=16445,Агеевка,ФАП,FAP,"ул. Сиреневая, 9, 213114, д. Агеевка, Могилевс...",NaN
1,Адамовский ФАП,https://healthcare.by/instinfo.php?orgnum=17185,Адамово,ФАП,FAP,"д. Адамово, Воложинский р-н, Минская обл.",NaN
2,Адаховщинский ФАП,https://healthcare.by/instinfo.php?orgnum=18082,Адаховщина,ФАП,FAP,"пер. Парковый, 10, 225372, д. Адаховщина, Ляхо...",NaN
3,Азделинский ФАП,https://healthcare.by/instinfo.php?orgnum=15701,Азделино,ФАП,FAP,"ул. Новая, 1а, 247025, д. Азделино, Гомельский...",NaN
4,Азинский ФАП,https://healthcare.by/instinfo.php?orgnum=15299,Азино,ФАП,FAP,"211424, д. Азино, Полоцкий р-н, Витебская обл.",NaN
...,...,...,...,...,...,...,...
3492,Филиал № 6 ГУЗ «Гомельская центральная городск...,https://healthcare.by/instinfo.php?orgnum=4673,Гомель,Поликлиника,Polyclinic,"ул. Новополесская, 11, 246003, г. Гомель",NaN
3493,Филиал №1 ГУЗ «ВГПЦ» городская поликлиника №1,https://healthcare.by/instinfo.php?orgnum=26881,Витебск,Поликлиника,Polyclinic,(vgcp.by),NaN
3494,Центральная городская стоматологическая поликл...,https://healthcare.by/instinfo.php?orgnum=5555,Гродно,Поликлиника,Polyclinic,"ул. Суворова, 21, 230001, г. Гродно",http://cgsp.by
3495,Центральная поликлиника Департамента финансов ...,https://healthcare.by/instinfo.php?orgnum=589,Минск,Поликлиника,Polyclinic,"ул. Мясникова, 25а, 220030, г. Минск",http://cpmvd.by
3496,Цетр стоматологии,https://healthcare.by/instinfo.php?orgnum=18137,Могилев,NaN,NaN,"б-р Ленина, 4, 212030, г. Могилев, ул. Миронов...",http://www.ohsp.by

Empty DataFrame
Columns: [facility_title, link, settlement, facility_type, facility_type_eng, address, website]
Index: []

In [77]:
# Select rows where both facility type columns are missing
missing_type = (
    df["facility_type"].isna()
    & df["facility_type_eng"].isna()
)

# Find hospital abbreviations:
# ЦКРБ, ЦРБ, ЦГБ, or УБ
hospital_mask = (
    missing_type
    & df["facility_title"].str.contains(
        r"(?<!\w)(?:ЦРКБ|ЦРБ|ЦГБ|УБ)(?!\w)",
        case=False,
        na=False,
        regex=True
    )
)

# Update hospital values
df.loc[
    hospital_mask,
    ["facility_type", "facility_type_eng"]
] = ["Больница", "Hospital"]


# Recalculate the missing-value mask after updating hospitals
missing_type = (
    df["facility_type"].isna()
    & df["facility_type_eng"].isna()
)

# Find outpatient clinic names and abbreviations
ambulatory_mask = (
    missing_type
    & (
        df["facility_title"].str.contains(
            r"(?<!\w)(?:АВОП|ВАП|АОП)(?!\w)"
            r"|БСУ\s+с\s+ВА"
            r"|врача\s+общей\s+практики",
            case=False,
            na=False,
            regex=True
        )
        |
        # Match standalone "ВА" only when written in uppercase
        df["facility_title"].str.contains(
            r"(?<!\w)ВА(?!\w)",
            case=True,
            na=False,
            regex=True
        )
    )
)

# Update outpatient clinic values
df.loc[
    ambulatory_mask,
    ["facility_type", "facility_type_eng"]
] = ["Амбулатория", "Outpatient Clinic"]

In [79]:
# Remove rows where either facility type column is still missing
df = df.dropna(
    subset=["facility_type", "facility_type_eng"]
).reset_index(drop=True)

In [84]:
# Remove rows where address column is still missing
df = df.dropna(
    subset=["address"]
).reset_index(drop=True)

In [85]:
df[df['address'].isna()]

Empty DataFrame
Columns: [facility_title, link, settlement, facility_type, facility_type_eng, address, website]
Index: []

## Checking scraped addresses

In [87]:
# Pattern for a domain appearing anywhere in the address
website_pattern = r"(?:https?://|www\.)?(?:[a-z0-9-]+\.)+[a-z]{2,}"

# Find rows where the address contains a website/domain
wrong_address_mask = df["address"].str.contains(
    website_pattern,
    case=False,
    na=False,
    regex=True
)

# Show suspicious rows
df.loc[
    wrong_address_mask,
    ["facility_title", "link", "address", "website"]
]

,facility_title,link,address,website
3471,Филиал №1 ГУЗ «ВГПЦ» городская поликлиника №1,https://healthcare.by/instinfo.php?orgnum=26881,(vgcp.by),NaN

In [101]:
import re

# Common address markers
address_markers = [
    "ул.",
    "пр.",
    "пр-т",
    "пер.",
    "пл.",
    "д.",
    "аг.",
    "агр.",
    "г.п.",
    "г.",
    "обл.",
    "р-н",
    "с/с",
    "п.",
]

# Build a regular expression for address markers
address_pattern = "|".join(
    re.escape(marker) for marker in address_markers
)

# Patterns that often indicate contact details or other non-address text
junk_pattern = (
    r"тел\.?|телефон|факс|"
    r"https?://|www\.|@|"
    r"\bГУЗ\b|\bУЗ\b"
)

# A Belarusian postal code usually contains 6 digits
postal_code_pattern = r"\b\d{6}\b"

# Address looks valid if it contains an address marker or postal code
looks_like_address = (
    df["address"].str.contains(
        address_pattern,
        case=False,
        na=False,
        regex=True
    )
    |
    df["address"].str.contains(
        postal_code_pattern,
        na=False,
        regex=True
    )
)

# Detect phone numbers, websites, email addresses, and institution names
looks_like_junk = df["address"].str.contains(
    junk_pattern,
    case=False,
    na=False,
    regex=True
)

# Find non-empty values that do not contain
# any address marker or postal code
suspicious_address_mask = (
    df["address"].notna()
    & ~looks_like_address
)

df.loc[
    suspicious_address_mask,
    ["facility_title", "link", "address", "website"]
]['address']

638               тел.: (02345) 3-66-88
2253              тел.: (01713) 7-60-18
2625             тел.: (0225)  43-68-52
2799    тел.: (0177) 95-61-04, 95-61-07
Name: address, dtype: str

In [99]:
suspicious_address_mask.sum()

np.int64(4)

In [100]:
import re

# Address markers
address_markers = [
    "ул.", "пр.", "пр-т", "пер.", "пл.", "д.",
    "аг.", "агр.", "г.п.", "г.", "обл.",
    "р-н", "с/с", "п."
]

address_pattern = "|".join(
    re.escape(marker) for marker in address_markers
)

postal_code_pattern = r"\b\d{6}\b"

# Re-scrape only suspicious rows
for index in df.index[suspicious_address_mask]:
    response = requests.get(df.at[index, "link"], timeout=30)
    response.raise_for_status()

    doc = BeautifulSoup(response.text, "html.parser")

    # Find the main facility information paragraph
    info = next(
        (p for p in doc.find_all("p") if p.find("b")),
        None
    )

    if info is None:
        continue

    # Extract all text fragments from the paragraph
    text_parts = [
        text.replace("\xa0", " ").strip(" ()")
        for text in info.stripped_strings
    ]

    # Keep only fragments that look like an address
    address_candidates = [
        text for text in text_parts
        if (
            re.search(postal_code_pattern, text)
            or re.search(address_pattern, text, flags=re.IGNORECASE)
        )
    ]

    # Use the first address-like fragment
    if address_candidates:
        df.at[index, "address"] = address_candidates[0]

    # Extract the website if it is a clickable link
    website_tag = info.select_one(
        'a[href^="http://"], a[href^="https://"]'
    )

    if website_tag:
        df.at[index, "website"] = website_tag.get("href")

In [97]:
df.loc[
    suspicious_address_mask,
    ["facility_title", "address", "website"]
]

,facility_title,address,website
638,Золотушский ФАП,тел.: (02345) 3-66-88,NaN
1008,"Ляховщинский ФАП, ФАП","211875, д. Ляховщина, Поставский р-н, Витебска...",NaN
1405,"Половский ФАП, Учреждение Здравоохранения «Пос...","211875, д. Полово, Поставский р-н, Витебская обл.",NaN
1857,Устянский ФАП,"Приозерная, 17, 213540, д. Устье, Чериковский ...",NaN
2103,"Амбулатория по ул. Славинского, 5, амбулатория","Амбулатория по ул. Славинского, 5",NaN
2253,Дубровская врачебная амбулатория общей практики,тел.: (01713) 7-60-18,NaN
2625,Титовская амбулатория врача общей практики,тел.: (0225) 43-68-52,NaN
2682,"Щорсовская амбулатория врача общей практики, а...","ул. Парковая, 23а, 231428, д. Щорсы, Новогрудс...",NaN
2799,Ганцевичская участковая больница,"тел.: (0177) 95-61-04, 95-61-07",NaN
3094,"Пышнянская больница сестринского ухода, больница","211199, д. Пышно, Лепельский р-н, Витебская обл.",NaN
3356,Детская поликлиника г. Слоним,Детская поликлиника г. Слоним,NaN
3361,Детская стоматологическая поликлиника г. Гродно,Филиал учреждения здравоохранения «Центральная...,NaN
3471,Филиал №1 ГУЗ «ВГПЦ» городская поликлиника №1,"ул. Терешковой, 30, 210009, г. Витебск",NaN

In [ ]:
повторная обработка

In [103]:
import re
import requests
from bs4 import BeautifulSoup

# Normalize text for comparison
title_text = df["facility_title"].fillna("").str.strip().str.lower()
address_text = df["address"].fillna("").str.strip().str.lower()

# Detect phone numbers or websites stored as an address
phone_or_website = df["address"].str.contains(
    r"^\s*(?:тел\.?|телефон|факс)"
    r"|https?://|www\."
    r"|(?:[a-z0-9-]+\.)+[a-z]{2,}",
    case=False,
    na=False,
    regex=True
)

# Detect cases where the address is identical to the facility title
same_as_title = (
    address_text.ne("")
    & address_text.eq(title_text)
)

# Detect institution descriptions without a postal code
institution_text = (
    ~df["address"].str.contains(r"\b\d{6}\b", na=False, regex=True)
    & df["address"].str.contains(
        r"\b(?:ГУЗ|УЗ|ЛПУ|ФАП|поликлиника|больница|амбулатория)\b"
        r"|учреждени[ея]\s+здравоохранения",
        case=False,
        na=False,
        regex=True
    )
)

# Select rows that need to be re-scraped
bad_address_mask = (
    phone_or_website
    | same_as_title
    | institution_text
)

df.loc[
    bad_address_mask,
    ["facility_title", "address", "link"]
]

,facility_title,address,link
638,Золотушский ФАП,тел.: (02345) 3-66-88,https://healthcare.by/instinfo.php?orgnum=15855
2253,Дубровская врачебная амбулатория общей практики,тел.: (01713) 7-60-18,https://healthcare.by/instinfo.php?orgnum=14134
2625,Титовская амбулатория врача общей практики,тел.: (0225) 43-68-52,https://healthcare.by/instinfo.php?orgnum=24959
2799,Ганцевичская участковая больница,"тел.: (0177) 95-61-04, 95-61-07",https://healthcare.by/instinfo.php?orgnum=6175
3356,Детская поликлиника г. Слоним,Детская поликлиника г. Слоним,https://healthcare.by/instinfo.php?orgnum=5905
3361,Детская стоматологическая поликлиника г. Гродно,Филиал учреждения здравоохранения «Центральная...,https://healthcare.by/instinfo.php?orgnum=5556

In [104]:
for index in df.index[bad_address_mask]:
    response = requests.get(df.at[index, "link"], timeout=30)
    response.raise_for_status()

    doc = BeautifulSoup(response.text, "html.parser")

    # Find the main facility information paragraph
    info = next(
        (p for p in doc.find_all("p") if p.find("b")),
        None
    )

    if info is None:
        df.at[index, "address"] = None
        continue

    # Extract separate text fragments from the paragraph
    text_parts = [
        text.replace("\xa0", " ").strip(" ()")
        for text in info.stripped_strings
    ]

    # Remove empty values, phone numbers and websites
    text_parts = [
        text for text in text_parts
        if text
        and not re.search(
            r"^(?:тел\.?|телефон|факс)"
            r"|https?://|www\."
            r"|(?:[a-z0-9-]+\.)+[a-z]{2,}$",
            text,
            flags=re.IGNORECASE
        )
    ]

    # First choice: a line containing a six-digit postal code
    address_candidates = [
        text for text in text_parts
        if re.search(r"\b\d{6}\b", text)
    ]

    # Fallback: a line containing an address marker and a number
    if not address_candidates:
        address_candidates = [
            text for text in text_parts
            if re.search(
                r"\b(?:ул\.|пр-т|пр\.|пер\.|пл\.|д\.|аг\.|агр\.|"
                r"г\.п\.|г\.|обл\.|р-н|с/с|п\.)",
                text,
                flags=re.IGNORECASE
            )
            and re.search(r"\d", text)
            and text.lower() != title_text.at[index]
        ]

    # Replace the incorrect value or use None if no address was found
    df.at[index, "address"] = (
        address_candidates[0]
        if address_candidates
        else None
    )

    # Extract the facility website when available
    website_tag = info.select_one(
        'a[href^="http://"], a[href^="https://"]'
    )

    if website_tag:
        df.at[index, "website"] = website_tag.get("href")

In [105]:
df.loc[
    df["address"].isna()
    | df["address"].str.contains(
        r"^\s*(?:тел\.?|телефон|факс)",
        case=False,
        na=False,
        regex=True
    ),
    ["facility_title", "address", "link"]
]

,facility_title,address,link
638,Золотушский ФАП,NaN,https://healthcare.by/instinfo.php?orgnum=15855
2253,Дубровская врачебная амбулатория общей практики,NaN,https://healthcare.by/instinfo.php?orgnum=14134
2625,Титовская амбулатория врача общей практики,NaN,https://healthcare.by/instinfo.php?orgnum=24959
2799,Ганцевичская участковая больница,NaN,https://healthcare.by/instinfo.php?orgnum=6175
3361,Детская стоматологическая поликлиника г. Гродно,NaN,https://healthcare.by/instinfo.php?orgnum=5556

In [106]:
df.to_csv("healthcare_facilities_healthcare.by.csv")

# GEOCODING

In [108]:
import os
from dotenv import load_dotenv
from dotenv import dotenv_values
load_dotenv()

GOOGLE_GEO_API_KEY = os.environ["GOOGLE_GEO_API_KEY"]
GOOGLE_PLACES_KEY = os.environ["GOOGLE_PLACES_KEY"]

In [109]:
for address in df["address"]:
    print(address)

ул. Сиреневая, 9, 213114, д. Агеевка, Могилевский р-н, Могилевская обл.
д. Адамово, Воложинский р-н, Минская обл.
пер. Парковый, 10, 225372, д. Адаховщина, Ляховичский р-н, Брестская обл.
ул. Новая, 1а, 247025, д. Азделино, Гомельский р-н, Гомельская обл.
211424, д. Азино, Полоцкий р-н, Витебская обл.
д. 9А, 247507, д. Александровка, Речицкий р-н, Гомельская обл.
ул. Первомайская, 85, 247718, д. Александровка, Калинковичский р-н, Гомельская обл.
ул. Ленина, 18, 225834, д. Алексеевичи, Дрогичинский р-н, Брестская обл.
д. Алексиничи, Сенненский р-н, Витебская обл.
213170, д. Олешковичи, Белыничский р-н, Могилевская обл.
п. Биозавода, Несвижский р-н, Минская обл.
211262, д. Амбросовичи, Шумилинский р-н, Витебская обл.
ул. Молодежная, 5, 213109, д. Амховая 1-я, Могилевский р-н, Могилевская обл.
д. Ананичи, Пуховичский р-н, Минская обл.
ул. Козлова, 1, 223741, д. Ананчицы, Солигорский р-н, Минская обл.
Юньковский с/с, 211875, д. Андроны, Поставский р-н, Витебская обл.
ул. Советская, 44А, 247730, д. Антоновка, Калинковичский р-н, Гомельская обл.
ул. Интернациональная, 12, 247248, д. Антоновка, Жлобинский р-н, Гомельская обл.
ул. Комсомольская, 37, 247073, д. Антоновка, Добрушский р-н, Гомельская обл.
ул. Юбилейная, 5, 213220, д. Антоновка, Чаусский р-н, Могилевская обл.
ул. Гагарина, 38, 211157, д. Антополье, Чашникский р-н, Витебская обл.
ул. Карвата, 1, 225314, д. Арабовщина, Барановичский р-н, Брестская обл.
ул. Советская, 37а, 247503, д. Артуки, Речицкий р-н, Гомельская обл.
ул. Колхозная, 6, 247662, д. Асаревичи, Брагинский р-н, Гомельская обл.
ул. Мамонтова, 5, 222673, аг. Аталезь, Столбцовский р-н, Минская обл.
ул. Школьная, 76, 211972, д. Ахремовцы, Браславский р-н, Витебская обл.
ул. Центральная, д. Большие Негновичи, Борисовский р-н, Минская обл.
д. Большое Осово, Крупский р-н, Минская обл.
Кирова, 52, 213879, д. Бабирово, Глусский р-н, Могилевская обл.
ул. Садовая, 1, д. Бабичи, Чечерский р-н, Гомельская обл.
ул. Мастрюкова, 17, 247534, д. Бабичи, Речицкий р-н, Гомельская обл.
ул. Шурина, 3, 247932, д. Бабуничи, Петриковский р-н, Гомельская обл.
211052, д. Баево, Дубровенский р-н, Витебская обл.
ул. Центральная, 71, 225142, д. Бакуны-1, Пружанский р-н, Брестская обл.
Ленина, 1, 213865, д. Балашевичи, Глусский р-н, Могилевская обл.
ул. Малькевича, 16, д. Балаши, Вилейский р-н, Минская обл.
231435, д. Барановичи, Кореличский р-н, Гродненская обл.
д. Бараново, Гродненский р-н, Гродненская обл.
ул. Молодежная, 10-1, 247753, д. Барбаров, Мозырский р-н, Гомельская обл.
Горбовский с/с, 211204, д. Барсеево, Лиозненский р-н, Витебская обл.
ул. Молодежная, 8, 211729, д. Барсуки, Докшицкий р-н, Витебская обл.
2136506, д. Барсуки, Климовичский р-н, Могилевская обл.
ул. Центральная, 27а, д. Барсуки, Кировский р-н, Могилевская обл.
д. Барсуки, Смолевичский р-н, Минская обл.
ул. Садовая, 2а, д. Барчицы, Кировский р-н, Могилевская обл.
ул. Школьная, 57, кв. 4, 213202, д. Барышевка, Чаусский р-н, Могилевская обл.
213484, д. Бастеновичи, Мстиславский р-н, Могилевская обл.
231371, д. Бастуны, Вороновский р-н, Гродненская обл.
ул. Садовая, 14, 225874, д. Батчи, Кобринский р-н, Брестская обл.
247356, д. Бацунь, Буда-Кошелевский р-н, Гомельская обл.
ул. Луговая, 20, 211279, д. Башни, Шумилинский р-н, Витебская обл.
р. Мурашки, 19, д. Безверховичи, Слуцкий р-н, Минская обл.
247560, д. Безуев, 98 Речицкий р-н, Гомельская обл.
ул. Первомайская, 19А, 247903, д. Белановичи, Петриковский р-н, Гомельская обл.
223114, д. Алекшицы, Логойский р-н, Минская обл.
213154, д. Белевичи, Могилевский р-н, Могилевская обл.
ул. Советская, 247962, д. Белев, Житковичский р-н, Гомельская обл.
ул. Комсомольская, 18а, 247202, д. Белица, Жлобинский р-н, Гомельская обл.
ул. Молодежная, 23, 247514, д. Белое Болото, Речицкий р-н, Гомельская обл.
ул. Школьная. 1, 213651, д. Белая Дуброва, Костюковичский р-н, Могилевская обл.
д. Белая Липа, Сенненский р-н, Витебская обл.
ул. Комсомольская, 14, 225178, свх. Белоусовщина, Пружанский р-н, Брестская обл.
211875, д. Бельки, Поставский р-н, Витебская обл.
211621, д. Бельковщина, Верхнедвинский р-н, Витебская обл.
ул. Советская, 21, 247763, д. Белая, Мозырский р-н, Гомельская обл.
ул. Советская, 3, 225865, д. Бельск, Кобринский р-н, Брестская обл.
ул. Новая,4, 247169, д. Беляевка, Чечерский р-н, Гомельская обл.
223137, д. Белое, Логойский р-н, Минская обл.
ул. Приозерная, 7а, 231415, д. Бенин, Новогрудский р-н, Гродненская обл.
247395, д. Ховхло, Буда-Кошелевский р-н, Гомельская обл.
пер. Советский, 7, 247964, д. Бережцы, Житковичский р-н, Гомельская обл.
ул. Ленинская, 247968, д. Березняки, Житковичский р-н, Гомельская обл.
ул. Мира, 8, 247733, д. Березняки, Калинковичский р-н, Гомельская обл.
ул. Клубная, 7, 213860, д. Березовичи, Бобруйский р-н, Могилевская обл.
ул. Центральная, 10, 225890, д. Береза, Кобринский р-н, Брестская обл.
213244, д. Березовка, Славгородский р-н, Могилевская обл.
ул. Садовая, 24Б, 211719, д. Березовка, Докшицкий р-н, Витебская обл.
ул. Молодежная, 35, 247723, д. Березовка, Калинковичский р-н, Гомельская обл.
ул. Молодежная, 1, 213884, д. Березовка, Глусский р-н, Могилевская обл.
ул. Центральная, 2, 225763, д. Березцы, Пинский р-н, Брестская обл.
213663, д. Беседы, Хотимский р-н, Могилевская обл.
ул. Школьная, 1А, 247900, д. Беседки, Петриковский р-н, Гомельская обл.
211915, д. Бильдюги, Шарковщинский р-н, Витебская обл.
213904, д. Биорда, Кличевский р-н, Могилевская обл.
231303, д. Бискупцы, Лидский р-н, Гродненская обл.
ул. Молодежная, 4, 213212, д. Благовичи, Чаусский р-н, Могилевская обл.
д. Блужа, Пуховичский р-н, Минская обл.
ул. Интернациональная, 27а, 247246, д. Бобовка, Жлобинский р-н, Гомельская обл.
ул. Садовая, 6-2, 247750, д. Бобренята, Мозырский р-н, Гомельская обл.
д. Бобровичи, Воложинский р-н, Минская обл.
247704, н.п. Бобровичи, Калинковичский р-н, Гомельская обл.
ул. Садовая, 2, 211057, д. Боброво, Дубровенский р-н, Витебская обл.
211197, д. Боброво, Лепельский р-н, Витебская обл.
Бобыничский с/с, ул. Школьная, 10, 211431, д. Бобыничи, Полоцкий р-н, Витебская обл.
д. Богданово, Сенненский р-н, Витебская обл.
231924, д. Богди, Волковысский р-н, Гродненская обл.
211995, д. Богино, Браславский р-н, Витебская обл.
ул. Советская, 6, 213843, д. Богушовка, Бобруйский р-н, Могилевская обл.
225732, д. Бокиничи, Пинский р-н, Брестская обл.
223640, д. Бокщицы, Слуцкий р-н, Минская обл.
д. Новый Болецк, Городокский р-н, Витебская обл.
211919, д. Болколы, Шарковщинский р-н, Витебская обл.
213142, д. Болонов-Селец, Быховский р-н, Могилевская обл.
247290, д. Болотня, Рогачевский р-н, Гомельская обл.
ул. Комсомольская, 13, 225890, д. Болота, Кобринский р-н, Брестская обл.
ул. Н. Село, 50, д. Болотчицы, Слуцкий р-н, Минская обл.
д. Больтеники, Вороновский р-н, Гродненская обл.
231399, д. Больтишки, Вороновский р-н, Гродненская обл.
пер. Школьный, 3, 247726, д. Великие Автюки, Калинковичский р-н, Гомельская обл.
ул. Центральная, 11, 225555, д. Большое Малешево, Столинский р-н, Брестская обл.
ул. Советская, 22б, д. Большие Орлы, Столинский р-н, Брестская обл.
231821, д. Большие Шиловичи, Слонимский р-н, Гродненская обл.
ул. Советская, 2, 225546, д. Бор Дубенец, Столинский р-н, Брестская обл.
211034, д. Борздовка, Оршанский р-н, Витебская обл.
213602, д. Борисовичи, Климовичский р-н, Могилевская обл.
247611, д. Борисовщина, Хойникский р-н, Гомельская обл.
225716, д. Боричевичи, Пинский р-н, Брестская обл.
ул. Юбилейная, 9, 225225, д. Борки, Березовский р-н, Брестская обл.
247981, д. Борки, Житковичский р-н, Гомельская обл.
ул. Заслонова, 1, 225443, д. Борки, Ганцевичский р-н, Брестская обл.
ул. 40 лет Победы, 225658, д. Боровцы, Лунинецкий р-н, Брестская обл.
ул. Школьная, 66 А, д. Боровики, Дзержинский р-н, Минская обл.
ул. Ленина, 18, 225656, д. Боровики, Лунинецкий р-н, Брестская обл.
ул. Центральная, 20а, д. Боровица, Кировский р-н, Могилевская обл.
пер. Мирный, 1а, 247183, д. Боровая Буда, Кормянский р-н, Гомельская обл.
ул. Школьная, 9, 247846, д. Боровое, Лельчицкий р-н, Гомельская обл.
д. Бородиничи, Браславский р-н, Витебская обл.
д. Бор, Пуховичский р-н, Минская обл.
ул. Молодежная, 14, 231425, д. Бор, Новогрудский р-н, Гродненская обл.
211794, д. Бортники, Глубокский р-н, Витебская обл.
ул. Школьная, 4, 211989, д. Боруны, Браславский р-н, Витебская обл.
д. 18 А, 247513, д. Кленовица, Речицкий р-н, Гомельская обл.
211205, д. Борщевка, Витебский р-н, Витебская обл.
ул. Ленина, 1а, 247087, д. Борщевка, Добрушский р-н, Гомельская обл.
ул. Совхозная 1-я, 4а, 247511, д. Борщевка, Речицкий р-н, Гомельская обл.
211957, д. Босянки, Миорский р-н, Витебская обл.
213676, д. Ботаево, Хотимский р-н, Могилевская обл.
ул. Трудовая,1, 247155, д. Ботвиново, Чечерский р-н, Гомельская обл.
ул. Советская, 38, 225735, д. Ботово, Пинский р-н, Брестская обл.
213661, д. Боханы, Хотимский р-н, Могилевская обл.
ул. Суворова, 2, 223860, д. Бояничи, Любанский р-н, Минская обл.
д. Бояры, Вилейский р-н, Минская обл.
211082, д. Браздетчино, Оршанский р-н, Витебская обл.
д. Братково, Копыльский р-н, Минская обл.
ул. Дорожная, 20, 247802, д. Братское, Наровлянский р-н, Гомельская обл.
ул. Школьная, 1, 225833, д. Брашевичи, Дрогичинский р-н, Брестская обл.
ул. Гагарина, 50, 247947, д. Бринёв, Петриковский р-н, Гомельская обл.
ул. Центральная, 1, д. Бровки, Минский р-н, Минская обл.
ул. Новая, 31а, 225668, д. Бродница, Лунинецкий р-н, Брестская обл.
ул. Мира, 92, 225173, д. Броды, Пружанский р-н, Брестская обл.
ул. Спортивная, 54, 222143, д. Броды, Борисовский р-н, Минская обл.
ул. Ленинская, 11а, 213833, п. Брожа, Бобруйский р-н, Могилевская обл.
ул. Центральная, 12а, 231404, д. Брольники, Новогрудский р-н, Гродненская обл.
ул. Первомайская, 1, д. Бронислав, Житковичский р-н, Гомельская обл.
ул. Колхозная, 6, 247516, д. Бронное, Речицкий р-н, Гомельская обл.
здание общежития в/ч 67878, 225213, д. Бронная Гора, Березовский р-н, Брестская обл.
ул. Юбилейная, 26, 213151, д. Брыли, Могилевский р-н, Могилевская обл.
ул. Молодежная, 28, д. Бубны, Вилейский р-н, Минская обл.
ул. Школьная, 5, 247860, д. Буда-Лельчицкая, Лельчицкий р-н, Гомельская обл.
247350, д. Буда-Люшево, Буда-Кошелевский р-н, Гомельская обл.
ул. Колхозная, 3, 247865, д. Буда-Софиевская, Лельчицкий р-н, Гомельская обл.
д. Будагово, Смолевичский р-н, Минская обл.
ул. Октябрьская, 8/1-2, 231107, д. Буденовка, Ошмянский р-н, Гродненская обл.
ул. Школьная, 25, д. Будилово, Бешенковичский р-н, Витебская обл.
213137, д. Будище, Могилевский р-н, Могилевская обл.
213914, д. Буднев, Кличевский р-н, Могилевская обл.
ул. Молодежная, 2, 247702, д. Смолинка, Калинковичский р-н, Гомельская обл.
ул. Задорожная, 3, 211044, д. Жабыки, Дубровенский р-н, Витебская обл.
213425, д. Буда, Горецкий р-н, Могилевская обл.
ул. Ленинская, 60, 247856, д. Букча, Лельчицкий р-н, Гомельская обл.
247708, д. Булавки, Калинковичский р-н, Гомельская обл.
ул. Кооперативная, 29, 247633, д. Бурки, Брагинский р-н, Гомельская обл.
ул. Я. Коласа, 225812, д. 5/2, Бусса, Ивановский р-н, Брестская обл.
ул. Советская, 7в, 225547, д. Бухличи, Столинский р-н, Брестская обл.
д. Бучатино, Копыльский р-н, Минская обл.
ул. Центральная, 30, д. Большой Быков, Слуцкий р-н, Минская обл.
ул. Центральная, 2А-1, 231221, д. Быстрица, Островецкий р-н, Гродненская обл.
ул. Центральная, 6, 211986, д. Быстромовцы, Браславский р-н, Витебская обл.
ул. Молодежная, 10а, д. Бытча, Борисовский р-н, Минская обл.
д. Большая Быховщина, Несвижский р-н, Минская обл.
ул. Ленина, 24, 225846, д. Вавуличи, Дрогичинский р-н, Брестская обл.
ул. Ленина, 105а, 225756, д. Валище, Пинский р-н, Брестская обл.
д. Ванелевичи, Копыльский р-н, Минская обл.
213660, д. Василевка 2-я, Хотимский р-н, Могилевская обл.
д. Василевщина, Минский р-н, Минская обл.
ул. Первомайская, 3, 247039, д. Василево, Гомельский р-н, Гомельская обл.
213260, д. Васьковичи, Славгородский р-н, Могилевская обл.
213240, д. Васьковичи, Чаусский р-н, Могилевская обл.
ул. Строительная, 15, 211154, д. Малая Ведрень, Чашникский р-н, Витебская обл.
ул. Школьная, 10, 247551, д. Ведрич, Речицкий р-н, Гомельская обл.
ул. Минская, 10, д. Вежа, Слуцкий р-н, Минская обл.
ул. Советская, 4а, д. Вейно, Могилевский р-н, Могилевская обл.
247935, д. Велавск, Петриковский р-н, Гомельская обл.
н. п. Велетин, 247606, д. Велетин, Хойникский р-н, Гомельская обл.
247142, ул. Победы, 1а, д. Великие Немки, Ветковский р-н, Гомельская обл.
ул. Пролетарская, 1, 213753, д. Великий Бор, Осиповичский р-н, Могилевская обл.
ул. Школьная, 4, 223228, д. Большая Ганута, Червенский р-н, Минская обл.
ул. Советская, 21, 225351, д. Великие Луки, Барановичский р-н, Брестская обл.
д. Великополье, Червенский р-н, Минская обл.
д. Великая Раевка, Копыльский р-н, Минская обл.
211918, д. Великое Село, Шарковщинский р-н, Витебская обл.
ул. Сельская, 16, д. Великое Село, Дзержинский р-н, Минская обл.
231971, д. Великое Село, Свислочский р-н, Гродненская обл.
ул. Победы, 9, 225165, д. Великое Село, Пружанский р-н, Брестская обл.
223618, д. Великая Слива, Слуцкий р-н, Минская обл.
ул. Школьная, 5, 225655, д. Велута, Лунинецкий р-н, Брестская обл.
ул. Садовая, 1Б, 225036, д. Вельямовичи, Брестский р-н, Брестская обл.
231488, д. Вензовец, Дятловский р-н, Гродненская обл.
ул. Советская, 47а, 247802, д. Вербовичи, Наровлянский р-н, Гомельская обл.
213716, д. Дражня, Осиповичский р-н, Могилевская обл.
Ширковский с/с, 211875, д. Вереньки, Поставский р-н, Витебская обл.
д. Верески, Борисовский р-н, Минская обл.
ул. Колхозная, 8, 247984, д. Вересница, Житковичский р-н, Гомельская обл.
ул. Школьная, 9, 211927, д. Веретеи, Шарковщинский р-н, Витебская обл.
д. Веречье, Городокский р-н, Витебская обл.
ул. Школьная, 13, 211493, д. Веркуды, Ушачский р-н, Витебская обл.
ул. Витебская, 6, 247225, д. Верхняя Олба, Жлобинский р-н, Гомельская обл.
ул. Центральная, 10, 211797, д. Верхнее, Глубокский р-н, Витебская обл.
Верховский с/с, ул. Фрунзе, 25, д. Верховье, Бешенковичский р-н, Витебская обл.
ул. Парковая, 5, 225863, д. Верхолесье, Кобринский р-н, Брестская обл.
222930, ул. Пролетарская, 57, д. Верхутино, Стародорожский р-н, Минская обл.
д. Веселово, Борисовский р-н, Минская обл.
ул. Школьная, 1, 223742, д. Веска, Солигорский р-н, Минская обл.
213692, д. Ветка, Хотимский р-н, Могилевская обл.
ул. Первомайская, 247965, д. Ветчин, Житковичский р-н, Гомельская обл.
ул. Молодежная, 2, 222331, д. Видевщина, Молодеченский р-н, Минская обл.
ул. Советская, 58, 225536, д. Видибор, Столинский р-н, Брестская обл.
211626, д. Видоки, Верхнедвинский р-н, Витебская обл.
213653, д. Видуйцы, Костюковичский р-н, Могилевская обл.
213862, д. Вильча, Глусский р-н, Могилевская обл.
231384, д. Винцуки, Вороновский р-н, Гродненская обл.
213905, д. Вирков, Кличевский р-н, Могилевская обл.
ул. Почтовая, 6, 211737, д. Витуничи, Докшицкий р-н, Витебская обл.
ул. Центральная, 122, 225652, д. Вичин, Лунинецкий р-н, Брестская обл.
ул. Лесная, 12, 213831, д. Вишневка, Бобруйский р-н, Могилевская обл.
д. Возгеляны, Браславский р-н, Витебская обл.
ул. Луговая, 10, 247151, п. Вознесенский, Чечерский р-н, Гомельская обл.
д. Войганы, Воложинский р-н, Минская обл.
231483, д. Войневичи, Дятловский р-н, Гродненская обл.
ул. Садовая, д. 61, 223214, аг. Войнилово, Червенский р-н, Минская обл.
ул. Окружная, 28а, 213211, д. Войнилы, Чаусский р-н, Могилевская обл.
ул. Центральная, 5а, 231921, д. Войтковичи, Волковысский р-н, Гродненская обл.
д. Войтово, Витебский р-н, Витебская обл.
ул. Центральная, 7, 213232, д. Волковичи, Чаусский р-н, Могилевская обл.
231405, д. Волковичи, Новогрудский р-н, Гродненская обл.
211875, д. Волки, Поставский р-н, Витебская обл.
211933, д. Волковщина, Миорский р-н, Витебская обл.
Китайско-Белорусский индустриальный парк «Великий камень», ул. Дружная, 1, 222231, д. Волма, Смолевичский р-н, Минская обл.
213944, д. Волосовичи, Кировский р-н, Могилевская обл.
ул. Песчаная, 28, 247304, д. Волосовичи, Октябрьский р-н, Гомельская обл.
213654, д. Волоськовка, Костюковичский р-н, Могилевская обл.
ул. Центральная, 23/2, 225352, д. Волохва, Барановичский р-н, Брестская обл.
213512, д. Волчес, Кричевский р-н, Могилевская обл.
ул. Пионерская, 9, 247176, д. Волынцы, Кормянский р-н, Гомельская обл.
д. Волька, Ивацевичский р-н, Брестская обл.
ул. Школьная, 23, 247187, д. Ворновка, Кормянский р-н, Гомельская обл.
ул. Центральная, 195, 231407, д. Большие Воробьевичи, Новогрудский р-н, Гродненская обл.
ул. Школьная, 1, 222138, д. Дедиловичи, Борисовский р-н, Минская обл.
пер. Школьный, 3, 225521, д. Ворони, Столинский р-н, Брестская обл.
ул. Советская, 4, 225153, д. Ворониловичи, Пружанский р-н, Брестская обл.
213330, д. Воронино, Быховский р-н, Могилевская обл.
д. Вороны, Витебский р-н, Витебская обл.
ул. Полоцкая, 3, 231221, д. Ворона, Островецкий р-н, Гродненская обл.
231454, д. Воронча, Кореличский р-н, Гродненская обл.
ул. Комсомольская, 13, 247711, д. Воротын, Калинковичский р-н, Гомельская обл.
ул. Пушкинская, 2г, 225808, д. Вороцевичи, Ивановский р-н, Брестская обл.
ул. Парковая 17 , 247179, д. Зятковичи, Кормянский р-н, Гомельская обл.
ул. Брестская, 7, 225536, д. Вулька-Орея, Столинский р-н, Брестская обл.
ул. Центральная, 18, 225731, д. Вулька-Городище, Пинский р-н, Брестская обл.
д. Вулька-Обровская, Ивацевичский р-н, Брестская обл.
ул. Жукова, 34/1, 225853, д. Вулька-Радовецкая, Дрогичинский р-н, Брестская обл.
ул. Новая, 23, 225652, д. Вулька 1, Лунинецкий р-н, Брестская обл.
ул. 8 Марта, 1, 225837, д. Вулька-Симоновичская, Дрогичинский р-н, Брестская обл.
ул. Мира. 3, 222330, д. Вывери, Молодеченский р-н, Минская обл.
д. Выгонощи, Ивацевичский р-н, Брестская обл.
д. Выдрица, Крупский р-н, Минская обл.
ул. Строителей, 16, 247189, д. Высокая, Кормянский р-н, Гомельская обл.
213607, д. Высокое, Климовичский р-н, Могилевская обл.
247278, д. Высокое, Рогачевский р-н, Гомельская обл.
д. Высокий Городец, Толочинский р-н, Витебская обл.
ул. Центральная, 33, 223315, д. Высокая Гора, Березинский р-н, Минская обл.
ул. Железнодорожная, 91г, 213041, д. Старое Высокое, Шкловский р-н, Могилевская обл.
ул. Луговая, 5, 247565, д. Вышемир, Речицкий р-н, Гомельская обл.
ул. Революционная, 1, 213713, д. Вязовница, Осиповичский р-н, Могилевская обл.
222322, д. Вязынка, Молодеченский р-н, Минская обл.
ул. Центральная, 18, 213711, д. Вязье, Осиповичский р-н, Могилевская обл.
ул. Центральная, 13, 211169, д. Вятеро, Чашникский р-н, Витебская обл.
д. Габриелевка, Пуховичский р-н, Минская обл.
213687, д. Гавриленка, Костюковичский р-н, Могилевская обл.
247260, д. Гадиловичи, Рогачевский р-н, Гомельская обл.
223121, д. Гайна, Логойский р-н, Минская обл.
213265, д. Гайшин, Славгородский р-н, Могилевская обл.
ул. Тихая, 19, 231341, д. Галимщина, Гродненская обл.
д. Заозерье, Несвижский р-н, Минская обл.
ул. Залинейная, 20, 225447, д. Ганцевичи, Ганцевичский р-н, Брестская обл.
ул. Победы, 13, д. Гапоновичи, Крупский р-н, Минская обл.
223311, д. Василевщина, Березинский р-н, Минская обл.
211812, д. Гатовщина, Глубокский р-н, Витебская обл.
ул. Октябрьская, 5а, 247301, д. Гать, Октябрьский р-н, Гомельская обл.
211659, д. Гвоздово, Полоцкий р-н, Витебская обл.
ул. Ленина, 16, 225926, д. Гвозница, Малоритский р-н, Брестская обл.
213242, д. Гиженка, Славгородский р-н, Могилевская обл.
231724, д. Гиновичи, Гродненский р-н, Гродненская обл.
211985, д. Гирейши, Браславский р-н, Витебская обл.
231395, д. Гирки, Вороновский р-н, Гродненская обл.
ул. Первомайская, 5, 225326, д. Гирматовцы, Барановичский р-н, Брестская обл.
247399, д. Глазовка, Буда-Кошелевский р-н, Гомельская обл.
ул. Центральная, 53 а, д. Гливин, Борисовский р-н, Минская обл.
ул. Белобережская, 62 а, 247765, д. Глиница, Мозырский р-н, Гомельская обл.
ул. Советская, 84, 225526, д. Глинка, Столинский р-н, Брестская обл.
ул. Центральная, 91, 247510, д. Глинная Слобода, Речицкий р-н, Гомельская обл.
ул. Советская, 1, 225844, д. Глинно, Ивановский р-н, Брестская обл.
213530, д. Глинь, Чериковский р-н, Могилевская обл.
ул. Центральная, 33, 225893, д. Глинянка, Кобринский р-н, Брестская обл.
ул. Советская, 45, 247522, д. Глыбов, Речицкий р-н, Гомельская обл.
ул. Лесная, 13, 247046, д. Глыбоцкое, Гомельский р-н, Гомельская обл.

# Find lat and long

In [110]:
import geocoder

g = geocoder.google('2950 Broadway, New York, NY', key=GOOGLE_GEO_API_KEY)
g.latlng
from geopy.geocoders import GoogleV3

geolocator = GoogleV3(GOOGLE_GEO_API_KEY)

In [32]:
# df["latitude"] = None
# df["longitude"] = None

# for i, address in enumerate(df["address"]):
#     location = geolocator.geocode(address)
#     if location:
#         df.loc[i, "latitude"] = location.latitude
#         df.loc[i, "longitude"] = location.longitude

In [125]:
# df["latitude"] = None
# df["longitude"] = None

# for i, address in enumerate(df["address"]):
#     if pd.isna(address):
#         address = df.loc[i, "facility_title"]

#     location = geolocator.geocode(address + ", Беларусь")

#     if location:
#         df.loc[i, "latitude"] = location.latitude
#         df.loc[i, "longitude"] = location.longitude

In [130]:
address = "Жарский с/с, ул. Центральная, 18, 211482, д. Жары, Ушачский р-н, Витебская обл."

location = geolocator.geocode(
    address,
    components={"country": "BY"},
    language="ru"
)

print(location.address)
print(location.latitude, location.longitude)

улица Центральная, Віцебская вобласць, Беларусь
55.1860129 29.0410481

In [131]:
df["latitude"] = None
df["longitude"] = None

for i, address in df["address"].items():
    if pd.isna(address):
        address = df.loc[i, "facility_title"]

    location = geolocator.geocode(address,
        components={"country": "BY"},
        language="ru")

    if location:
        df.loc[i, "latitude"] = location.latitude
        df.loc[i, "longitude"] = location.longitude

In [128]:
df.index.equals(pd.RangeIndex(len(df)))

True

In [ ]:
тест яндекса

In [135]:
import os
import requests
from dotenv import load_dotenv

# Reload the current value from .env
load_dotenv(override=True)

api_key = os.getenv("YANDEX_API_KEY", "").strip()

print("Key loaded:", bool(api_key))
print("Key length:", len(api_key))

response = requests.get(
    "https://geocode-maps.yandex.ru/v1/",
    params={
        "apikey": api_key,
        "geocode": "Минск",
        "format": "json"
    },
    timeout=30
)

print("Status:", response.status_code)
print(response.text)

Key loaded: True
Key length: 36
Status: 200
{"response":{"GeoObjectCollection":{"metaDataProperty":{"GeocoderResponseMetaData":{"request":"Минск","results":"10","found":"10"}},"featureMember":[{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"other","text":"Беларусь, Минск","kind":"locality","Address":{"country_code":"BY","formatted":"Беларусь, Минск","Components":[{"kind":"country","name":"Беларусь"},{"kind":"province","name":"Минск"},{"kind":"locality","name":"Минск"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, Минск","CountryNameCode":"BY","CountryName":"Беларусь","AdministrativeArea":{"AdministrativeAreaName":"Минск","Locality":{"LocalityName":"Минск"}}}}}},"name":"Минск","description":"Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.374425 53.793885","upperCorner":"28.080581 53.97162"}},"uri":"ymapsbm1://geo?data=Cgg1MzE3NzAxORIc0JHQtdC70LDRgNGD0YHRjCwg0JzRltC90YHQuiIKDaJ-3EEV8ZtXQg,,","Point":{"pos":"27.561831 53.902284"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"other","text":"Беларусь, Минск, Национальный аэропорт Минск","kind":"airport","Address":{"country_code":"BY","formatted":"Беларусь, Минск, Национальный аэропорт Минск","Components":[{"kind":"country","name":"Беларусь"},{"kind":"province","name":"Минск"},{"kind":"airport","name":"Национальный аэропорт Минск"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, Минск, Национальный аэропорт Минск","CountryNameCode":"BY","CountryName":"Беларусь","AdministrativeArea":{"AdministrativeAreaName":"Минск","Locality":{"DependentLocality":{"DependentLocalityName":"Национальный аэропорт Минск"}}}}}}},"name":"Национальный аэропорт Минск","description":"Минск, Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.999841 53.862361","upperCorner":"28.079656 53.912913"}},"uri":"ymapsbm1://geo?data=CgoxNTE5OTg5NzUzElDQkdC10LvQsNGA0YPRgdGMLCDQnNGW0L3RgdC6LCDQndCw0YbRi9GP0L3QsNC70YzQvdGLINCw0Y3RgNCw0L_QvtGA0YIg0JzRltC90YHQuiIKDcNF4EEVrY5XQg,,","Point":{"pos":"28.034066 53.889332"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"street","text":"Молдова, Кишинёв, улица Минск","kind":"street","Address":{"country_code":"MD","formatted":"Молдова, Кишинёв, улица Минск","Components":[{"kind":"country","name":"Молдова"},{"kind":"area","name":"муниципий Кишинёв"},{"kind":"locality","name":"Кишинёв"},{"kind":"street","name":"улица Минск"}]},"AddressDetails":{"Country":{"AddressLine":"Молдова, Кишинёв, улица Минск","CountryNameCode":"MD","CountryName":"Молдова","AdministrativeArea":{"AdministrativeAreaName":"муниципий Кишинёв","Locality":{"LocalityName":"Кишинёв","Thoroughfare":{"ThoroughfareName":"улица Минск"}}}}}}},"name":"улица Минск","description":"Кишинёв, Молдова","boundedBy":{"Envelope":{"lowerCorner":"28.860822 46.997489","upperCorner":"28.870353 47.001871"}},"uri":"ymapsbm1://geo?data=CgoxNTE0NzY3ODA4EiFNb2xkb3ZhLCBDaGnImWluxIN1LCBzdHJhZGEgTWluc2siCg2q7OZBFbz_O0I,","Point":{"pos":"28.865556 46.999738"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"other","text":"Россия, Красноярский край, Большемуртинско-Сухобузимский муниципальный округ, деревня Минск","kind":"locality","Address":{"country_code":"RU","formatted":"Россия, Красноярский край, Большемуртинско-Сухобузимский муниципальный округ, деревня Минск","Components":[{"kind":"country","name":"Россия"},{"kind":"province","name":"Сибирский федеральный округ"},{"kind":"province","name":"Красноярский край"},{"kind":"area","name":"Большемуртинско-Сухобузимский муниципальный округ"},{"kind":"locality","name":"деревня Минск"}]},"AddressDetails":{"Country":{"AddressLine":"Россия, Красноярский край, Большемуртинско-Сухобузимский муниципальный округ, деревня Минск","CountryNameCode":"RU","CountryName":"Россия","AdministrativeArea":{"AdministrativeAreaName":"Красноярский край","SubAdministrativeArea":{"SubAdministrativeAreaName":"Большемуртинско-Сухобузимский муниципальный округ","Locality":{"LocalityName":"деревня Минск"}}}}}}},"name":"деревня Минск","description":"Большемуртинско-Сухобузимский муниципальный округ, Красноярский край, Россия","boundedBy":{"Envelope":{"lowerCorner":"93.326029 57.095468","upperCorner":"93.348037 57.101213"}},"uri":"ymapsbm1://geo?data=Cgg1MzExMTQ2NxKrAdCg0L7RgdGB0LjRjywg0JrRgNCw0YHQvdC-0Y_RgNGB0LrQuNC5INC60YDQsNC5LCDQkdC-0LvRjNGI0LXQvNGD0YDRgtC40L3RgdC60L4t0KHRg9GF0L7QsdGD0LfQuNC80YHQutC40Lkg0LzRg9C90LjRhtC40L_QsNC70YzQvdGL0Lkg0L7QutGA0YPQsywg0LTQtdGA0LXQstC90Y8g0JzQuNC90YHQuiIKDYasukIVqmRkQg,,","Point":{"pos":"93.336961 57.098304"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"street","text":"Беларусь, М-1","kind":"street","Address":{"country_code":"BY","formatted":"Беларусь, М-1","Components":[{"kind":"country","name":"Беларусь"},{"kind":"street","name":"М-1"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, М-1","CountryNameCode":"BY","CountryName":"Беларусь","Thoroughfare":{"ThoroughfareName":"М-1"}}}}},"name":"М-1","description":"Беларусь","boundedBy":{"Envelope":{"lowerCorner":"23.565658 52.115471","upperCorner":"30.987763 54.690855"}},"uri":"ymapsbm1://geo?data=CggzMTExMDY5NBIW0JHQtdC70LDRgNGD0YHRjCwg0JwtMSIKDdQG2kEVnbRWQg,,","Point":{"pos":"27.253332 53.676378"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"other","text":"Беларусь, Минск, экспериментальный многофункциональный комплекс Минск-Мир","kind":"district","Address":{"country_code":"BY","formatted":"Беларусь, Минск, экспериментальный многофункциональный комплекс Минск-Мир","Components":[{"kind":"country","name":"Беларусь"},{"kind":"province","name":"Минск"},{"kind":"locality","name":"Минск"},{"kind":"district","name":"экспериментальный многофункциональный комплекс Минск-Мир"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, Минск, экспериментальный многофункциональный комплекс Минск-Мир","CountryNameCode":"BY","CountryName":"Беларусь","AdministrativeArea":{"AdministrativeAreaName":"Минск","Locality":{"LocalityName":"Минск","DependentLocality":{"DependentLocalityName":"экспериментальный многофункциональный комплекс Минск-Мир"}}}}}}},"name":"экспериментальный многофункциональный комплекс Минск-Мир","description":"Минск, Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.522557 53.856589","upperCorner":"27.559801 53.873441"}},"uri":"ymapsbm1://geo?data=CgoyMTEzOTQ5NzYzEoYB0JHQtdC70LDRgNGD0YHRjCwg0JzRltC90YHQuiwg0Y3QutGB0L_QtdGA0YvQvNC10L3RgtCw0LvRjNC90Ysg0YjQvNCw0YLRhNGD0L3QutGG0YvRj9C90LDQu9GM0L3RiyDQutC-0LzQv9C70LXQutGBINCc0ZbQvdGB0Lot0KHQstC10YIiCg1lW9xBFcd2V0I,","Point":{"pos":"27.544628 53.865993"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"street","text":"Беларусь, М-6","kind":"street","Address":{"country_code":"BY","formatted":"Беларусь, М-6","Components":[{"kind":"country","name":"Беларусь"},{"kind":"street","name":"М-6"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, М-6","CountryNameCode":"BY","CountryName":"Беларусь","Thoroughfare":{"ThoroughfareName":"М-6"}}}}},"name":"М-6","description":"Беларусь","boundedBy":{"Envelope":{"lowerCorner":"23.659657 53.5215","upperCorner":"27.409612 54.066095"}},"uri":"ymapsbm1://geo?data=CggzMTExMDY5OBIW0JHQtdC70LDRgNGD0YHRjCwg0JwtNiIKDY9RzEEVsV1XQg,,","Point":{"pos":"25.539822 53.841493"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"street","text":"Беларусь, М-2","kind":"street","Address":{"country_code":"BY","formatted":"Беларусь, М-2","Components":[{"kind":"country","name":"Беларусь"},{"kind":"street","name":"М-2"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, М-2","CountryNameCode":"BY","CountryName":"Беларусь","Thoroughfare":{"ThoroughfareName":"М-2"}}}}},"name":"М-2","description":"Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.73464 53.890579","upperCorner":"28.034992 54.015824"}},"uri":"ymapsbm1://geo?data=CggzMTMwNjMwNhIW0JHQtdC70LDRgNGD0YHRjCwg0JwtMiIKDVZf30EVvfVXQg,,","Point":{"pos":"27.921552 53.989982"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"street","text":"Беларусь, М-3","kind":"street","Address":{"country_code":"BY","formatted":"Беларусь, М-3","Components":[{"kind":"country","name":"Беларусь"},{"kind":"street","name":"М-3"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, М-3","CountryNameCode":"BY","CountryName":"Беларусь","Thoroughfare":{"ThoroughfareName":"М-3"}}}}},"name":"М-3","description":"Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.632699 53.961318","upperCorner":"30.122667 55.155895"}},"uri":"ymapsbm1://geo?data=CggzMTExMDY5NRIW0JHQtdC70LDRgNGD0YHRjCwg0JwtMyIKDfgc5UEVtDFbQg,,","Point":{"pos":"28.639145 54.79854"}}},{"GeoObject":{"metaDataProperty":{"GeocoderMetaData":{"precision":"other","text":"Беларусь, Белорусская железная дорога, станция Минск-Северный","kind":"railway_station","Address":{"country_code":"BY","formatted":"Беларусь, Белорусская железная дорога, станция Минск-Северный","Components":[{"kind":"country","name":"Беларусь"},{"kind":"route","name":"Белорусская железная дорога"},{"kind":"railway_station","name":"станция Минск-Северный"}]},"AddressDetails":{"Country":{"AddressLine":"Беларусь, Белорусская железная дорога, станция Минск-Северный","CountryNameCode":"BY","CountryName":"Беларусь","Country":{"Locality":{}}}}}},"name":"станция Минск-Северный","description":"Белорусская железная дорога, Беларусь","boundedBy":{"Envelope":{"lowerCorner":"27.517643 53.901042","upperCorner":"27.5341 53.91076"}},"uri":"ymapsbm1://geo?data=CgkxMDAxMjIzOTISYdCR0LXQu9Cw0YDRg9GB0YwsINCR0LXQu9Cw0YDRg9GB0LrQsNGPINGH0YvQs9GD0L3QutCwLCDRgdGC0LDQvdGG0YvRjyDQnNGW0L3RgdC6LdCf0LDRntC90L7Rh9C90YsiCg38NNxBFaWfV0I,","Point":{"pos":"27.525872 53.905902"}}}]}}}

In [136]:
# Load API key from .env
load_dotenv(override=True)
api_key = os.getenv("YANDEX_API_KEY")

addresses = {
    "Светочский ФАП":
        "ул. Совхозная, 1а, 225210, д. Светоч, Березовский р-н, Брестская обл.",

    "Завечельский ФАП":
        "Сорочинский с/с, ул. Центральная, 21, 211498, д. Завечелье, Ушачский р-н, Витебская обл.",

    "Песковская амбулатория общей практики":
        "пер. Школьный, 5, 231600, д. Пески, Мостовский р-н, Гродненская обл.",

    "Якшанский ФАП":
        "ул. Октябрьская, 20, 225803, д. Якша, Ивановский р-н, Брестская обл.",

    "Жарский ФАП":
        "Жарский с/с, ул. Центральная, 18, 211482, д. Жары, Ушачский р-н, Витебская обл."
}

for title, address in addresses.items():
    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",
            "bbox": "23.1,51.2~32.8,56.3",
            "rspn": 1,
            "results": 1
        },
        timeout=30
    )

    response.raise_for_status()
    data = response.json()

    results = data["response"]["GeoObjectCollection"]["featureMember"]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns longitude first, then latitude
        longitude, latitude = geo_object["Point"]["pos"].split()

        metadata = geo_object["metaDataProperty"]["GeocoderMetaData"]

        print(title)
        print("Found address:", metadata.get("text"))
        print("Precision:", metadata.get("precision"))
        print("Latitude:", latitude)
        print("Longitude:", longitude)
        print()
    else:
        print(title)
        print("Not found")
        print()

Светочский ФАП
Found address: Беларусь, Брестская область, Берёзовский сельсовет, деревня Светоч, Совхозная улица, 1А
Precision: exact
Latitude: 52.488707
Longitude: 24.92365

Завечельский ФАП
Found address: Беларусь, Витебская область, Ушачский район, Сорочинский сельсовет, деревня Завечелье, Центральная улица, 21
Precision: exact
Latitude: 55.130024
Longitude: 28.744607

Песковская амбулатория общей практики
Found address: Беларусь, Гродненская область, Мостовский район, агрогородок Лунно, Школьный переулок, 5
Precision: exact
Latitude: 53.455425
Longitude: 24.260756

Якшанский ФАП
Found address: Беларусь, Брестская область, Ивановский район, Бродницкий сельсовет, деревня Якша, Октябрьская улица, 20
Precision: exact
Latitude: 52.164282
Longitude: 25.73614

Жарский ФАП
Found address: Беларусь, Витебская область, Ушачский район, деревня Жары, Центральная улица, 18
Precision: exact
Latitude: 55.078767
Longitude: 28.651973

In [137]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv


# Reload environment variables from the .env file.
# override=True is important in Jupyter because an old key may remain in memory.
load_dotenv(override=True)

api_key = os.getenv("YANDEX_API_KEY")

if not api_key:
    raise ValueError("YANDEX_API_KEY was not found in the .env file")


# Unique links of the facilities that must be geocoded again with Yandex.
# We use links instead of facility names because names may be duplicated,
# while orgnum in each link identifies a specific facility.
test_links = [
    "https://healthcare.by/instinfo.php?orgnum=17198",
    "https://healthcare.by/instinfo.php?orgnum=15458",
    "https://healthcare.by/instinfo.php?orgnum=12328",
    "https://healthcare.by/instinfo.php?orgnum=17822",
    "https://healthcare.by/instinfo.php?orgnum=15457",
]


# Create a Boolean mask:
# True means that the row belongs to one of the selected facilities.
test_mask = df["link"].isin(test_links)


# Check that all requested facilities were found in the DataFrame.
found_links = set(df.loc[test_mask, "link"])
missing_links = set(test_links) - found_links

print(f"Facilities found: {test_mask.sum()} of {len(test_links)}")

if missing_links:
    print("Links not found in the DataFrame:")
    for link in missing_links:
        print(link)


# Optional safety check:
# the same facility link should normally appear only once.
if df.loc[test_mask, "link"].duplicated().any():
    raise ValueError("Duplicate facility links were found in the selected rows")


# df.index[test_mask] returns the real DataFrame index labels
# of the selected facilities.
#
# This is safer than enumerate(), because enumerate() always creates
# numbers 0, 1, 2, 3..., which may not match the actual DataFrame index.
for i in df.index[test_mask]:

    # Read the address from the exact row identified by index label i.
    address = df.at[i, "address"]

    # If the address is missing, use the facility title and settlement
    # as a fallback search query.
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # Send the address to the Yandex Geocoder API.
    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",

            # Approximate bounding box of Belarus.
            "bbox": "23.1,51.2~32.8,56.3",

            # Restrict results to the specified bounding box.
            "rspn": 1,

            # Return only the best matching result.
            "results": 1,
        },
        timeout=30,
    )

    # Stop and show an error if Yandex returns an unsuccessful response.
    response.raise_for_status()

    data = response.json()

    # Extract the list of geocoding results.
    results = data[
        "response"
    ][
        "GeoObjectCollection"
    ][
        "featureMember"
    ]

    if results:
        # Yandex returns coordinates in this order:
        # longitude latitude
        longitude, latitude = (
            results[0]["GeoObject"]["Point"]["pos"].split()
        )

        # Write the coordinates back to the same DataFrame row.
        #
        # df.at[i, ...] uses the real index label i, so the result
        # cannot accidentally be written to another facility.
        df.at[i, "latitude"] = float(latitude)
        df.at[i, "longitude"] = float(longitude)

        print(
            df.at[i, "facility_title"],
            "->",
            latitude,
            longitude
        )

    else:
        print(
            df.at[i, "facility_title"],
            "-> not found"
        )

Facilities found: 5 of 5
Жарский ФАП -> 55.078767 28.651973
Завечельский ФАП -> 55.130024 28.744607
Светочский ФАП -> 52.488707 24.92365
Якшанский ФАП -> 52.164282 25.73614
Песковская амбулатория общей рактики -> 53.455425 24.260756

взять еще 500 рандомных фапов, для которых мы нашли координаты в гугл и проверить их в яндексе, сравнить с гугл, и заодно переписать их в датафрейме - боюсь, даже если гугл нашел в рб, то это может быть не всегда верная локация

In [138]:
import os
import time
import requests
import pandas as pd
from math import radians, sin, cos, sqrt, atan2
from dotenv import load_dotenv


# Reload the Yandex API key from .env
load_dotenv(override=True)
api_key = os.getenv("YANDEX_API_KEY")

if not api_key:
    raise ValueError("YANDEX_API_KEY was not found in .env")


# Calculate the distance between Google and Yandex coordinates in kilometers
def calculate_distance(lat1, lon1, lat2, lon2):
    earth_radius = 6371

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    latitude_difference = lat2 - lat1
    longitude_difference = lon2 - lon1

    a = (
        sin(latitude_difference / 2) ** 2
        + cos(lat1)
        * cos(lat2)
        * sin(longitude_difference / 2) ** 2
    )

    return 2 * earth_radius * atan2(sqrt(a), sqrt(1 - a))


# Select FAP rows for which Google found both coordinates
fap_candidates = df[
    (df["facility_type"] == "ФАП")
    & df["latitude"].notna()
    & df["longitude"].notna()
]


# Select up to 500 random FAPs.
# random_state=42 makes the sample reproducible:
# running this cell again selects the same facilities.
sample_size = min(500, len(fap_candidates))

sample_indices = fap_candidates.sample(
    n=sample_size,
    random_state=42
).index


# Store comparison results here.
# This list does not add extra columns to the main DataFrame.
comparison_rows = []


# Use the real DataFrame index for every selected facility.
# This guarantees that Yandex coordinates are written back
# to the same row from which the address was taken.
for i in sample_indices:

    address = df.at[i, "address"]

    # Use facility title and settlement if the address is missing
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # Save the existing Google coordinates before replacing them
    google_latitude = float(df.at[i, "latitude"])
    google_longitude = float(df.at[i, "longitude"])

    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",

            # Approximate boundaries of Belarus
            "bbox": "23.1,51.2~32.8,56.3",

            # Restrict the search to the bounding box
            "rspn": 1,

            # Return only the best result
            "results": 1,
        },
        timeout=30,
    )

    response.raise_for_status()
    data = response.json()

    results = data[
        "response"
    ][
        "GeoObjectCollection"
    ][
        "featureMember"
    ]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns coordinates as:
        # longitude latitude
        yandex_longitude, yandex_latitude = map(
            float,
            geo_object["Point"]["pos"].split()
        )

        metadata = geo_object[
            "metaDataProperty"
        ][
            "GeocoderMetaData"
        ]

        # Calculate the distance between the old Google point
        # and the new Yandex point
        distance_km = calculate_distance(
            google_latitude,
            google_longitude,
            yandex_latitude,
            yandex_longitude,
        )

        # Save comparison information separately
        comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": yandex_latitude,
            "yandex_longitude": yandex_longitude,
            "distance_km": distance_km,
            "yandex_address": metadata.get("text"),
            "yandex_precision": metadata.get("precision"),
        })

        # Replace Google coordinates in the original DataFrame
        # using the exact original DataFrame index
        df.at[i, "latitude"] = yandex_latitude
        df.at[i, "longitude"] = yandex_longitude

    else:
        comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": None,
            "yandex_longitude": None,
            "distance_km": None,
            "yandex_address": None,
            "yandex_precision": None,
        })

    # Small pause between API requests
    time.sleep(0.1)


# Create a temporary DataFrame for comparison
comparison_df = pd.DataFrame(comparison_rows)

print("Selected FAPs:", sample_size)
print("Found by Yandex:", comparison_df["yandex_latitude"].notna().sum())

Selected FAPs: 500
Found by Yandex: 500

In [139]:
comparison_df.sort_values(
    "distance_km",
    ascending=False
).head(30)

,df_index,facility_title,address,google_latitude,google_longitude,yandex_latitude,yandex_longitude,distance_km,yandex_address,yandex_precision
433,2495,Осиновский ФАП,"ул. Почтовая, 1, 213205, д. Осиновка, Чаусский...",53.943016,27.706895,53.849142,31.217525,230.235885,"Беларусь, Могилёвская область, Чаусский район,...",exact
0,1644,Слободской ФАП,"ул. Школьная, 2, 211328, д. Слобода, Витебский...",55.641159,27.034763,55.398426,30.607291,226.478133,"Беларусь, Витебский район, Задубровский сельсо...",exact
64,1746,Сторожовецкий ФАП,"ул. Советская, 3, 247990, д. Сторожовцы, Житко...",52.327501,30.463163,52.032943,27.783823,185.585556,"Беларусь, Гомельская область, Житковичский рай...",exact
80,122,Боровиковский ФАП,"ул. Ленина, 18, 225656, д. Боровики, Лунинецки...",52.214042,24.358489,52.517256,26.940080,178.487272,"Беларусь, Брестская область, Лунинецкий район,...",exact
466,1076,Милевичский ФАП,"ул. Первомайская, 12, 247976, д. Милевичи, Жит...",52.895237,30.053784,52.466048,27.601887,172.030739,"Беларусь, Гомельская область, Житковичский рай...",exact
140,1225,Новский ФАП,"ул. Гагарина, 30, 225211, д. Новое, Березовски...",52.072421,27.339084,52.483239,25.061146,161.558627,"Беларусь, Брестская область, Берёзовский район...",exact
78,434,Добринский ФАП,"ул. Центральная, 25, 211054, д. Добринь, Дубро...",54.622626,28.706808,54.646698,31.015979,148.631720,"Беларусь, Витебская область, Дубровенский райо...",near
162,1311,Отрадненский ФАП,"ул. Молодежная, 16, 223837, д. Отрадное, Любан...",53.858493,27.689160,52.715426,27.782197,127.253622,"Беларусь, Минская область, Любанский район, Ре...",exact
56,1353,Пересудовичский ФАП,"п/о Высокое, ул. Кирова, 5, 225217, д. Высокое...",52.366211,23.376775,52.401243,25.111209,117.777749,"Беларусь, Брестская область, Берёзовский район...",exact
139,242,Войтовский ФАП,"д. Войтово, Витебский р-н, Витебская обл.",55.295983,28.758363,55.217686,30.518052,111.847594,"Беларусь, Витебский район, Вымнянский сельсове...",other
369,731,Кировский ФАП,"ул. Школьная, 17, 223616, д. Кирово, Слуцкий р...",53.878453,27.437085,52.960402,27.537945,102.301137,"Беларусь, Минская область, Слуцкий район, Киро...",other
23,445,Докудовский ФАП,"ул. Полевая, 61А3, д. Докудово, Крупский р-н, ...",53.875644,27.582448,54.327756,28.897482,99.388149,"Беларусь, Минская область, Крупский район, Хот...",number
398,309,Глинковский ФАП,"ул. Советская, 84, 225526, д. Глинка, Столинск...",52.143876,25.505698,51.892055,26.857938,96.677205,"Беларусь, Брестская область, Столин, Советская...",exact
451,2519,Плюсский ФАП,"ул. Приозерная, 10, 211977, д. Плюсы, Браславс...",55.200011,27.688541,55.813283,27.047447,79.245668,"Беларусь, Витебская область, Браславский район...",near
334,346,Горковский ФАП,"ул. Центральная, 25, 223230, д. Горки, Червенс...",53.871632,27.651440,53.649829,28.622301,68.417655,"Беларусь, Минская область, Червенский район, Л...",near
155,1410,Полочанский ФАП,"ул. Советская, 59а, 222312, д. Полочаны, Молод...",53.896614,27.549051,54.223848,26.709833,65.755266,"Беларусь, Минская область, Молодечненский райо...",exact
380,1972,Хоновский ФАП,"213151, д. Борок, Могилевский р-н, Могилевская...",53.461579,29.703588,53.813358,30.293132,55.142041,"Беларусь, Могилёвский район",other
489,706,Каменский ФАП,"ул. Центральная, 108, 223411, д. Каменка, Узде...",53.875671,27.656094,53.501988,27.151822,53.188754,"Беларусь, Минская область, Узденский сельсовет...",exact
30,71,Березняковский ФАП,"ул. Ленинская, 247968, д. Березняки, Житковичс...",52.029171,27.637007,52.491898,27.497898,52.316662,"Беларусь, Гомельская область, Житковичский рай...",other
181,66,Беляевский ФАП,"ул. Новая,4, 247169, д. Беляевка, Чечерский р-...",52.510372,30.936792,52.960820,31.024639,50.435528,"Беларусь, Гомельская область, Чечерский район,...",exact
54,1487,Раевский ФАП,"ул. Ленина, 17а, 222332, д. Раевка, Молодеченс...",53.898443,27.561947,54.305614,27.225520,50.308709,"Беларусь, Минская область, Молодечненский райо...",exact
75,2016,Черский ФАП,"ул. Новая, 11, 225022, д. Черск, Брестский р-н...",52.159991,23.771062,51.713411,23.690667,49.962388,"Беларусь, Брестский район, Домачевский сельсов...",exact
159,1817,Трудовской ФАП,"ул. Центральная, 24, 211651, д. Труды, Полоцки...",55.485644,28.720128,55.636260,29.387387,45.178545,"Беларусь, Витебская область, Полоцкий район, М...",exact
190,628,Зеленевичский ФАП,"ул. Центральная, 19, 225156, д. Зеленевичи, Пр...",52.601734,24.397936,52.927458,24.723209,42.317448,"Беларусь, Брестская область, Пружанский район,...",exact
168,1267,Ольшанский ФАП,"ул. Центральная, 14, 211155, д. Ольшанка, Чашн...",54.852945,29.219130,54.620860,28.713678,41.459075,"Беларусь, Витебская область, Чашникский район,...",exact
425,74,Березовский ФАП,"ул. Центральная, 10, 225890, д. Береза, Кобрин...",52.120133,23.855347,52.333574,24.337876,40.539000,"Беларусь, Брестская область, Кобринский район,...",near
488,776,Колоднянский ФАП,"ул. Гагарина, 6, 225523, д. Колодно, Столински...",52.076082,27.340838,51.897591,26.863059,38.266809,"Беларусь, Брестская область, Столин, улица Гаг...",exact
402,195,Великоборский ФАП,"ул. Пролетарская, 1, 213753, д. Великий Бор, О...",53.337181,28.662239,53.216847,28.161969,35.852647,"Беларусь, Могилёвская область, Осиповичский ра...",exact
211,191,Вейнянский ФАП,"ул. Советская, 4а, д. Вейно, Могилевский р-н, ...",53.519964,30.256203,53.826588,30.385982,35.150347,"Беларусь, Могилёвский район, агрогородок Вейно...",exact
103,1737,Степской ФАП,"ул. Молодежная, 10, 247234, д. Степы, Жлобинск...",52.626180,29.718712,52.928685,29.618084,34.311263,"Беларусь, Гомельская область, Жлобинский район...",exact

In [ ]:
проверить новые 500 фапов в яндексе

In [140]:
# Get indexes of facilities already checked with Yandex
checked_indices = set(comparison_df["df_index"])


# Select FAPs that:
# 1. have coordinates;
# 2. have not yet been checked with Yandex.
new_candidates = df[
    (df["facility_type"] == "ФАП")
    & df["latitude"].notna()
    & df["longitude"].notna()
    & ~df.index.isin(checked_indices)
]


# Select up to 500 new random facilities
sample_size = min(500, len(new_candidates))

new_sample_indices = new_candidates.sample(
    n=sample_size,
    random_state=43
).index


# Store comparison results for the new batch
new_comparison_rows = []


for i in new_sample_indices:
    address = df.at[i, "address"]

    # Use facility title and settlement if address is missing
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # These are still the original Google coordinates,
    # because this facility has not been checked before
    google_latitude = float(df.at[i, "latitude"])
    google_longitude = float(df.at[i, "longitude"])

    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",
            "bbox": "23.1,51.2~32.8,56.3",
            "rspn": 1,
            "results": 1,
        },
        timeout=30,
    )

    response.raise_for_status()
    data = response.json()

    results = data[
        "response"
    ][
        "GeoObjectCollection"
    ][
        "featureMember"
    ]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns longitude first, then latitude
        yandex_longitude, yandex_latitude = map(
            float,
            geo_object["Point"]["pos"].split()
        )

        metadata = geo_object[
            "metaDataProperty"
        ][
            "GeocoderMetaData"
        ]

        distance_km = calculate_distance(
            google_latitude,
            google_longitude,
            yandex_latitude,
            yandex_longitude,
        )

        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": yandex_latitude,
            "yandex_longitude": yandex_longitude,
            "distance_km": distance_km,
            "yandex_address": metadata.get("text"),
            "yandex_precision": metadata.get("precision"),
        })

        # Replace Google coordinates with Yandex coordinates
        # in the same original DataFrame row
        df.at[i, "latitude"] = yandex_latitude
        df.at[i, "longitude"] = yandex_longitude

    else:
        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": None,
            "yandex_longitude": None,
            "distance_km": None,
            "yandex_address": None,
            "yandex_precision": None,
        })

    time.sleep(0.1)


# Create comparison data for this new batch
new_comparison_df = pd.DataFrame(new_comparison_rows)


# Add the new batch to the previous comparison results
comparison_df = pd.concat(
    [comparison_df, new_comparison_df],
    ignore_index=True
)

print("New facilities selected:", sample_size)
print(
    "Found by Yandex:",
    new_comparison_df["yandex_latitude"].notna().sum()
)
print("Total facilities checked:", len(comparison_df))

New facilities selected: 500
Found by Yandex: 500
Total facilities checked: 1000

еще 700 фапов

In [141]:
# Get indexes of all facilities already checked with Yandex
checked_indices = set(comparison_df["df_index"])


# Select FAPs that:
# 1. have coordinates;
# 2. have not yet been checked with Yandex.
new_candidates = df[
    (df["facility_type"] == "ФАП")
    & df["latitude"].notna()
    & df["longitude"].notna()
    & ~df.index.isin(checked_indices)
]


# Select up to 700 new random FAPs
sample_size = min(700, len(new_candidates))

new_sample_indices = new_candidates.sample(
    n=sample_size,
    random_state=44
).index


# Store comparison results for this batch
new_comparison_rows = []


for i in new_sample_indices:
    address = df.at[i, "address"]

    # Use facility title and settlement if the address is missing
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # Save the current coordinates before replacing them
    google_latitude = float(df.at[i, "latitude"])
    google_longitude = float(df.at[i, "longitude"])

    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",
            "bbox": "23.1,51.2~32.8,56.3",
            "rspn": 1,
            "results": 1,
        },
        timeout=30,
    )

    response.raise_for_status()
    data = response.json()

    results = data[
        "response"
    ][
        "GeoObjectCollection"
    ][
        "featureMember"
    ]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns longitude first, then latitude
        yandex_longitude, yandex_latitude = map(
            float,
            geo_object["Point"]["pos"].split()
        )

        metadata = geo_object[
            "metaDataProperty"
        ][
            "GeocoderMetaData"
        ]

        distance_km = calculate_distance(
            google_latitude,
            google_longitude,
            yandex_latitude,
            yandex_longitude,
        )

        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": yandex_latitude,
            "yandex_longitude": yandex_longitude,
            "distance_km": distance_km,
            "yandex_address": metadata.get("text"),
            "yandex_precision": metadata.get("precision"),
        })

        # Replace the current coordinates with Yandex coordinates
        # in the same original DataFrame row
        df.at[i, "latitude"] = yandex_latitude
        df.at[i, "longitude"] = yandex_longitude

    else:
        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": None,
            "yandex_longitude": None,
            "distance_km": None,
            "yandex_address": None,
            "yandex_precision": None,
        })

    time.sleep(0.1)


# Create comparison data for the new batch
new_comparison_df = pd.DataFrame(new_comparison_rows)


# Add the new batch to all previous comparison results
comparison_df = pd.concat(
    [comparison_df, new_comparison_df],
    ignore_index=True
)


print("New facilities selected:", sample_size)
print(
    "Found by Yandex:",
    new_comparison_df["yandex_latitude"].notna().sum()
)
print("Total facilities checked:", len(comparison_df))

New facilities selected: 700
Found by Yandex: 700
Total facilities checked: 1700

In [142]:
len(df)

3474

In [144]:
df.groupby('facility_type').size()

facility_type
Амбулатория     671
Больница        422
Поликлиника     265
ФАП            2116
dtype: int64

In [ ]:
все оставшиеся фапы

In [145]:
# Get indexes of all facilities already checked with Yandex
checked_indices = set(comparison_df["df_index"])


# Select every remaining FAP that:
# 1. has coordinates;
# 2. has not yet been checked with Yandex.
remaining_faps = df[
    (df["facility_type"] == "ФАП")
    & df["latitude"].notna()
    & df["longitude"].notna()
    & ~df.index.isin(checked_indices)
]

remaining_indices = remaining_faps.index

print("Remaining FAPs:", len(remaining_indices))


# Store comparison results for this batch
new_comparison_rows = []


for i in remaining_indices:
    address = df.at[i, "address"]

    # Use facility title and settlement if the address is missing
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # Save the current Google coordinates before replacing them
    google_latitude = float(df.at[i, "latitude"])
    google_longitude = float(df.at[i, "longitude"])

    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",
            "bbox": "23.1,51.2~32.8,56.3",
            "rspn": 1,
            "results": 1,
        },
        timeout=30,
    )

    response.raise_for_status()
    data = response.json()

    results = data[
        "response"
    ][
        "GeoObjectCollection"
    ][
        "featureMember"
    ]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns longitude first, then latitude
        yandex_longitude, yandex_latitude = map(
            float,
            geo_object["Point"]["pos"].split()
        )

        metadata = geo_object[
            "metaDataProperty"
        ][
            "GeocoderMetaData"
        ]

        # Calculate the distance between Google and Yandex coordinates
        distance_km = calculate_distance(
            google_latitude,
            google_longitude,
            yandex_latitude,
            yandex_longitude,
        )

        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "facility_type": df.at[i, "facility_type"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": yandex_latitude,
            "yandex_longitude": yandex_longitude,
            "distance_km": distance_km,
            "yandex_address": metadata.get("text"),
            "yandex_precision": metadata.get("precision"),
        })

        # Replace Google coordinates in the original DataFrame
        # using the exact index of this facility
        df.at[i, "latitude"] = yandex_latitude
        df.at[i, "longitude"] = yandex_longitude

    else:
        # Keep Google coordinates if Yandex found nothing
        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "facility_type": df.at[i, "facility_type"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": None,
            "yandex_longitude": None,
            "distance_km": None,
            "yandex_address": None,
            "yandex_precision": None,
        })

    time.sleep(0.1)


# Add this batch to the previous comparison results
new_comparison_df = pd.DataFrame(new_comparison_rows)

comparison_df = pd.concat(
    [comparison_df, new_comparison_df],
    ignore_index=True
)


print("Processed:", len(new_comparison_df))
print(
    "Found by Yandex:",
    new_comparison_df["yandex_latitude"].notna().sum()
)
print(
    "FAPs still unchecked:",
    (
        (df["facility_type"] == "ФАП")
        & ~df.index.isin(comparison_df["df_index"])
    ).sum()
)

Remaining FAPs: 416
Processed: 416
Found by Yandex: 416
FAPs still unchecked: 0

все амбулатории

In [146]:
# Select all outpatient clinics
ambulatory_indices = df.index[
    df["facility_type"] == "Амбулатория"
]

print("Outpatient clinics to process:", len(ambulatory_indices))


# Store comparison results for this batch
new_comparison_rows = []


for i in ambulatory_indices:
    address = df.at[i, "address"]

    # Use facility title and settlement if the address is missing
    if pd.isna(address) or not str(address).strip():
        address = (
            str(df.at[i, "facility_title"])
            + ", "
            + str(df.at[i, "settlement"])
        )

    # Save the current Google coordinates before replacing them
    google_latitude = df.at[i, "latitude"]
    google_longitude = df.at[i, "longitude"]

    response = requests.get(
        "https://geocode-maps.yandex.ru/v1/",
        params={
            "apikey": api_key,
            "geocode": address,
            "format": "json",
            "lang": "ru_RU",
            "bbox": "23.1,51.2~32.8,56.3",
            "rspn": 1,
            "results": 1,
        },
        timeout=30,
    )

    response.raise_for_status()
    data = response.json()

    results = data["response"]["GeoObjectCollection"]["featureMember"]

    if results:
        geo_object = results[0]["GeoObject"]

        # Yandex returns longitude first, then latitude
        yandex_longitude, yandex_latitude = map(
            float,
            geo_object["Point"]["pos"].split()
        )

        metadata = geo_object["metaDataProperty"]["GeocoderMetaData"]

        # Calculate distance only if Google coordinates exist
        if pd.notna(google_latitude) and pd.notna(google_longitude):
            distance_km = calculate_distance(
                float(google_latitude),
                float(google_longitude),
                yandex_latitude,
                yandex_longitude,
            )
        else:
            distance_km = None

        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "facility_type": df.at[i, "facility_type"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": yandex_latitude,
            "yandex_longitude": yandex_longitude,
            "distance_km": distance_km,
            "yandex_address": metadata.get("text"),
            "yandex_precision": metadata.get("precision"),
        })

        # Replace coordinates in the same original DataFrame row
        df.at[i, "latitude"] = yandex_latitude
        df.at[i, "longitude"] = yandex_longitude

    else:
        # Keep the existing coordinates if Yandex found nothing
        new_comparison_rows.append({
            "df_index": i,
            "facility_title": df.at[i, "facility_title"],
            "facility_type": df.at[i, "facility_type"],
            "address": address,
            "google_latitude": google_latitude,
            "google_longitude": google_longitude,
            "yandex_latitude": None,
            "yandex_longitude": None,
            "distance_km": None,
            "yandex_address": None,
            "yandex_precision": None,
        })

    time.sleep(0.1)


# Add this batch to the comparison table
new_comparison_df = pd.DataFrame(new_comparison_rows)

comparison_df = pd.concat(
    [comparison_df, new_comparison_df],
    ignore_index=True
)


print("Processed:", len(new_comparison_df))
print(
    "Found by Yandex:",
    new_comparison_df["yandex_latitude"].notna().sum()
)

Outpatient clinics to process: 671

HTTPError: 403 Client Error: Forbidden for url: https://geocode-maps.yandex.ru/v1/?apikey=7e986c4a-dae7-4a27-afb0-ca02548d2a92&geocode=%D0%BF%D0%B5%D1%80.+%D0%97%D0%B5%D0%BB%D0%B5%D0%BD%D1%8B%D0%B9%2C+4%D0%B0%2C+225811%2C+%D0%B4.+%D0%A0%D1%83%D0%B4%D1%81%D0%BA%2C+%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D1%80-%D0%BD%2C+%D0%91%D1%80%D0%B5%D1%81%D1%82%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB.&format=json&lang=ru_RU&bbox=23.1%2C51.2~32.8%2C56.3&rspn=1&results=1

In [147]:
# Convert successfully processed rows from this interrupted batch
partial_comparison_df = pd.DataFrame(new_comparison_rows)

# Add only rows that are not already present in comparison_df
partial_comparison_df = partial_comparison_df[
    ~partial_comparison_df["df_index"].isin(comparison_df["df_index"])
]

comparison_df = pd.concat(
    [comparison_df, partial_comparison_df],
    ignore_index=True
)

print("Processed before the error:", len(partial_comparison_df))

Processed before the error: 461

In [148]:
# Find outpatient clinics that have not yet been processed by Yandex
remaining_ambulatory = df[
    (df["facility_type"] == "Амбулатория")
    & ~df.index.isin(comparison_df["df_index"])
]

print("Outpatient clinics remaining:", len(remaining_ambulatory))

Outpatient clinics remaining: 210

In [133]:
#df.to_csv("healthcare_facilities_healthcare.by_with_coordinates3.csv")

In [150]:
comparison_df.to_csv("gathered_yandex_coordinates.csv")

In [149]:
df.to_csv("healthcare_with_coordinates_with_yandex.csv")

In [151]:
df

,facility_title,link,settlement,facility_type,facility_type_eng,address,website,latitude,longitude
0,Агеевский ФАП,https://healthcare.by/instinfo.php?orgnum=16445,Агеевка,ФАП,FAP,"ул. Сиреневая, 9, 213114, д. Агеевка, Могилевс...",NaN,53.959718,30.48202
1,Адамовский ФАП,https://healthcare.by/instinfo.php?orgnum=17185,Адамово,ФАП,FAP,"д. Адамово, Воложинский р-н, Минская обл.",NaN,54.138781,26.308645
2,Адаховщинский ФАП,https://healthcare.by/instinfo.php?orgnum=18082,Адаховщина,ФАП,FAP,"пер. Парковый, 10, 225372, д. Адаховщина, Ляхо...",NaN,53.153936,26.180716
3,Азделинский ФАП,https://healthcare.by/instinfo.php?orgnum=15701,Азделино,ФАП,FAP,"ул. Новая, 1а, 247025, д. Азделино, Гомельский...",NaN,52.540376,30.744805
4,Азинский ФАП,https://healthcare.by/instinfo.php?orgnum=15299,Азино,ФАП,FAP,"211424, д. Азино, Полоцкий р-н, Витебская обл.",NaN,55.623392,28.643457
...,...,...,...,...,...,...,...,...,...
3469,Филиал № 6 ГУЗ «Гомельская центральная городск...,https://healthcare.by/instinfo.php?orgnum=4744,Гомель,Поликлиника,Polyclinic,"пр. Победы, 6, 246022, г. Гомель",http://https//gcgdp.by/ru/o-filiale-6/administ...,52.434359,31.005047
3470,Филиал № 6 ГУЗ «Гомельская центральная городск...,https://healthcare.by/instinfo.php?orgnum=4673,Гомель,Поликлиника,Polyclinic,"ул. Новополесская, 11, 246003, г. Гомель",NaN,52.440964,30.999183
3471,Филиал №1 ГУЗ «ВГПЦ» городская поликлиника №1,https://healthcare.by/instinfo.php?orgnum=26881,Витебск,Поликлиника,Polyclinic,"ул. Терешковой, 30, 210009, г. Витебск",NaN,55.193559,30.248739
3472,Центральная городская стоматологическая поликл...,https://healthcare.by/instinfo.php?orgnum=5555,Гродно,Поликлиника,Polyclinic,"ул. Суворова, 21, 230001, г. Гродно",http://cgsp.by,53.66036,23.812129
3473,Центральная поликлиника Департамента финансов ...,https://healthcare.by/instinfo.php?orgnum=589,Минск,Поликлиника,Polyclinic,"ул. Мясникова, 25а, 220030, г. Минск",http://cpmvd.by,53.898776,27.546162

In [152]:
comparison_df

,df_index,facility_title,address,google_latitude,google_longitude,yandex_latitude,yandex_longitude,distance_km,yandex_address,yandex_precision,facility_type
0,1644,Слободской ФАП,"ул. Школьная, 2, 211328, д. Слобода, Витебский...",55.641159,27.034763,55.398426,30.607291,226.478133,"Беларусь, Витебский район, Задубровский сельсо...",exact,NaN
1,1495,Рассветовский ФАП,"ул. Центральная, 39б, 223722, д. Рассвет, Соли...",52.815878,27.536414,52.830161,27.251562,19.205774,"Беларусь, Минская область, Солигорский район, ...",exact,NaN
2,262,Воронский ФАП,"ул. Полоцкая, 3, 231221, д. Ворона, Островецки...",54.757295,25.956963,54.637814,25.985135,13.408403,"Беларусь, Гродненская область, Островецкий рай...",exact,NaN
3,437,Добромысленский ФАП,"д. Добромысель, Ивацевичский р-н, Брестская обл.",52.824549,25.708395,52.824437,25.713889,0.369361,"Беларусь, Брестская область, Ивацевичский райо...",other,NaN
4,1530,Рудаяворский ФАП,"231486, д. Руда Яворская, Дятловский р-н, Грод...",53.404221,25.111776,53.402911,25.111461,0.147100,"Беларусь, Гродненская область, Дятловский райо...",other,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2572,2565,Роднянская амбулатория врача общей практики,"ул. Больничная, 213621, д. Родня, Климовичский...",53.514216,32.137208,53.610957,32.089035,11.217737,"Беларусь, Могилёвская область, Климовичский район",other,Амбулатория
2573,2566,Рожанковская амбулатория врача общей практики,"ул. Щучинская, 22а, 231500, д. Рожанка, Щучинс...",53.538879,24.740801,53.525627,24.705153,2.778886,"Беларусь, Гродненская область, Щучинский район...",number,Амбулатория
2574,2568,Рудня-Маримоновская АОП,"ул. Центральная, 5, 247033, д. Рудня-Маримонов...",52.273161,30.730107,52.162935,30.716166,12.293312,"Беларусь, Гомельский район, деревня Рудня Мари...",other,Амбулатория
2575,2569,Руднянская АВОП,"ул. Молодежная, 3, 247755, д. Малая Рудня, Моз...",52.054806,29.226198,51.883584,29.198975,19.130112,"Беларусь, Гомельская область, Мозырский район,...",exact,Амбулатория
2576,2570,Руднянская врачебная амбулатория,"ул. Советская, 1, 223221, аг. Рудня, Червенски...",53.712564,28.424960,53.885602,28.373998,19.529891,"Беларусь, Минская область, Червенский район, Р...",exact,Амбулатория

повторно перенести все сохранённые координаты из comparison_df в основной df

In [153]:
# Keep the latest successful Yandex result for each original df row
updates = (
    comparison_df
    .dropna(subset=["yandex_latitude", "yandex_longitude"])
    .drop_duplicates(subset="df_index", keep="last")
    .copy()
)

# Keep only indexes that still exist in df
updates = updates[
    updates["df_index"].isin(df.index)
]


# Verify that df indexes still belong to the same facilities
index_check = updates[["df_index", "facility_title"]].copy()

index_check["current_df_title"] = index_check["df_index"].map(
    df["facility_title"]
)

mismatches = index_check[
    index_check["facility_title"] != index_check["current_df_title"]
]

print("Yandex updates found:", len(updates))
print("Index mismatches:", len(mismatches))

Yandex updates found: 2577
Index mismatches: 0

In [154]:
# Use df_index as the index of the update table
updates = updates.set_index("df_index")

# Write all successful Yandex coordinates back into df
df.loc[updates.index, "latitude"] = pd.to_numeric(
    updates["yandex_latitude"],
    errors="coerce"
)

df.loc[updates.index, "longitude"] = pd.to_numeric(
    updates["yandex_longitude"],
    errors="coerce"
)

print("Coordinates updated:", len(updates))

Coordinates updated: 2577

In [155]:
df.loc[
    df["facility_title"].str.contains(
        "Завечельский",
        case=False,
        na=False
    ),
    [
        "facility_title",
        "address",
        "latitude",
        "longitude"
    ]
]

,facility_title,address,latitude,longitude
555,Завечельский ФАП,"Сорочинский с/с, ул. Центральная, 21, 211498, ...",55.130024,28.744607

Points outside Belarus

In [156]:
latitude = pd.to_numeric(df["latitude"], errors="coerce")
longitude = pd.to_numeric(df["longitude"], errors="coerce")

outside_belarus = df[
    latitude.notna()
    & longitude.notna()
    & (
        (latitude < 51.2)
        | (latitude > 56.3)
        | (longitude < 23.1)
        | (longitude > 32.8)
    )
]

print("Points outside Belarus:", len(outside_belarus))

outside_belarus[
    [
        "facility_title",
        "facility_type",
        "address",
        "latitude",
        "longitude"
    ]
]

Points outside Belarus: 0

Empty DataFrame
Columns: [facility_title, facility_type, address, latitude, longitude]
Index: []

In [157]:
df.to_csv("healthcare_with_coordinates_with_yandex.csv")

In [159]:
df.columns

Index(['facility_title', 'link', 'settlement', 'facility_type',
       'facility_type_eng', 'address', 'website', 'latitude', 'longitude'],
      dtype='str')

# Добавляем области и районы

In [160]:
import pandas as pd
import geopandas as gpd


# Keep all original columns
df_geo = df.copy()


# Ensure coordinates are numeric
df_geo["latitude"] = pd.to_numeric(
    df_geo["latitude"],
    errors="coerce",
)

df_geo["longitude"] = pd.to_numeric(
    df_geo["longitude"],
    errors="coerce",
)


# Create point geometry
# X = longitude, Y = latitude
df_gdf = gpd.GeoDataFrame(
    df_geo,
    geometry=gpd.points_from_xy(
        df_geo["longitude"],
        df_geo["latitude"],
    ),
    crs="EPSG:4326",
)


# Read administrative districts
adm2 = gpd.read_file(
    "gadm41_BLR.gpkg",
    layer="ADM_ADM_2",
)

adm2 = adm2[
    ["NAME_1", "NAME_2", "geometry"]
].copy()


# Match coordinate systems
adm2 = adm2.to_crs(df_gdf.crs)


# Add region and district to every facility
df_gdf = gpd.sjoin(
    df_gdf,
    adm2,
    how="left",
    predicate="within",
)


# Remove technical join column
df_gdf = df_gdf.drop(
    columns="index_right",
    errors="ignore",
)


# Rename administrative columns
df_gdf = df_gdf.rename(
    columns={
        "NAME_1": "region",
        "NAME_2": "district",
    }
)


# Update the original DataFrame
df["region"] = df_gdf["region"]
df["district"] = df_gdf["district"]


# Save GeoPackage with all columns and geometry
df_gdf.to_file(
    "healthcare_regions.gpkg",
    layer="healthcare",
    driver="GPKG",
    index=False,
)


# Save CSV with all original columns plus region and district
df_gdf.drop(columns="geometry").to_csv(
    "healthcare_regions.csv",
    index=False,
    encoding="utf-8-sig",
)

In [161]:
df

,facility_title,link,settlement,facility_type,facility_type_eng,address,website,latitude,longitude,region,district
0,Агеевский ФАП,https://healthcare.by/instinfo.php?orgnum=16445,Агеевка,ФАП,FAP,"ул. Сиреневая, 9, 213114, д. Агеевка, Могилевс...",NaN,53.959718,30.48202,Mogilev,Mogilev
1,Адамовский ФАП,https://healthcare.by/instinfo.php?orgnum=17185,Адамово,ФАП,FAP,"д. Адамово, Воложинский р-н, Минская обл.",NaN,54.138781,26.308645,Minsk,Valozhyn
2,Адаховщинский ФАП,https://healthcare.by/instinfo.php?orgnum=18082,Адаховщина,ФАП,FAP,"пер. Парковый, 10, 225372, д. Адаховщина, Ляхо...",NaN,53.153936,26.180716,Brest,Baranavichy
3,Азделинский ФАП,https://healthcare.by/instinfo.php?orgnum=15701,Азделино,ФАП,FAP,"ул. Новая, 1а, 247025, д. Азделино, Гомельский...",NaN,52.540376,30.744805,Gomel,Gomyel
4,Азинский ФАП,https://healthcare.by/instinfo.php?orgnum=15299,Азино,ФАП,FAP,"211424, д. Азино, Полоцкий р-н, Витебская обл.",NaN,55.623392,28.643457,Vitebsk,Polatsak
...,...,...,...,...,...,...,...,...,...,...,...
3469,Филиал № 6 ГУЗ «Гомельская центральная городск...,https://healthcare.by/instinfo.php?orgnum=4744,Гомель,Поликлиника,Polyclinic,"пр. Победы, 6, 246022, г. Гомель",http://https//gcgdp.by/ru/o-filiale-6/administ...,52.434359,31.005047,Gomel,Gomyel
3470,Филиал № 6 ГУЗ «Гомельская центральная городск...,https://healthcare.by/instinfo.php?orgnum=4673,Гомель,Поликлиника,Polyclinic,"ул. Новополесская, 11, 246003, г. Гомель",NaN,52.440964,30.999183,Gomel,Gomyel
3471,Филиал №1 ГУЗ «ВГПЦ» городская поликлиника №1,https://healthcare.by/instinfo.php?orgnum=26881,Витебск,Поликлиника,Polyclinic,"ул. Терешковой, 30, 210009, г. Витебск",NaN,55.193559,30.248739,Vitebsk,Vitebsk
3472,Центральная городская стоматологическая поликл...,https://healthcare.by/instinfo.php?orgnum=5555,Гродно,Поликлиника,Polyclinic,"ул. Суворова, 21, 230001, г. Гродно",http://cgsp.by,53.66036,23.812129,Grodno,Hrodna
3473,Центральная поликлиника Департамента финансов ...,https://healthcare.by/instinfo.php?orgnum=589,Минск,Поликлиника,Polyclinic,"ул. Мясникова, 25а, 220030, г. Минск",http://cpmvd.by,53.898776,27.546162,Minsk,Minsk

In [ ]:
# df_gdf.to_file(
#     "healthcare_regions.gpkg",
#     driver="GPKG",
# )

In [ ]:
# df_gdf.to_csv("healthcare_regions.csv")

In [165]:
df[df['facility_title'].str.contains('Холомерь', na=False)]

Empty DataFrame
Columns: [facility_title, link, settlement, facility_type, facility_type_eng, address, website, latitude, longitude, region, district]
Index: []